const PROJECT_AUTHOR = 'Bach Truong';

const CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: '✨' },
  { id: 'trom-cap', label: 'Trộm cắp & Cướp giật', icon: '🚨' },
  { id: 'gay-roi', label: 'Gây rối trật tự công cộng', icon: '⚠️' },
  { id: 'ca-do', label: 'Cá độ & Cờ bạc', icon: '🎲' },
  { id: 'to-giac', label: 'Tố giác & Cảnh giác', icon: '👁️' },
];

const CONTENT_ITEMS = [
  {
    id: 1,
    title: 'Ví Ơi Đừng Bay',
    subtitle: 'Trộm Cắp Trên Xe Buýt',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'bus',
    hook: 'Anh kiểm tra túi em từ bao giờ vậy? 👀',
    duration: '28 giây',
    location: 'Tuyến xe buýt Phương Liệt — giờ cao điểm',
    mood: 'Hài hước → Twist "đứng hình" → Nghiêm túc',
    viralScore: 94,
    viralLikes: '12.4K',
    viralComments: '386',
    summary:
      'Tiểu phẩm kinh điển kiểu "cringe comedy": BXC ngồi cạnh hành khách, mắt nhìn túi xách như đang đọc trộm đề thi. Mỗi lần chạm túi là một lần "tôi không làm gì đâu". Cú twist cuối khiến cả xe buýt phải cười — và người xem nhớ mãi: đừng để ví bay.',
    storyboard: [
      { time: '0:00', title: 'Hook 3 giây', desc: 'BXC nhìn chằm chằm vào túi xách mở, nhạc trending bật.', overlay: 'POV: Kẻ trộm trên xe buýt 🚌' },
      { time: '0:05', title: 'Hành động hài', desc: 'Tay lén chạm túi, mặt "vô tội" cực đại.', overlay: 'Tôi chỉ... kiểm tra khóa thôi mà!' },
      { time: '0:12', title: 'Đối thoại viral', desc: 'Nạn nhân quay sang, câu thoại hook.', overlay: 'Ví em sắp bay rồi đấy anh!' },
      { time: '0:18', title: 'Twist', desc: 'Lôi thẻ công an — BXC đứng hình 2 giây.', overlay: 'Plot twist: Nạn nhân là Công an 👮' },
      { time: '0:24', title: 'Outro', desc: 'Logo Công an Phường Phương Liệt + hotline.', overlay: 'Đừng để ví bay! Gọi 113' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Chị ơi, túi chị không khóa à? Em... em lo cho chị thôi!' },
      { speaker: 'Nạn nhân', line: 'Anh kiểm tra lâu thế. Ví em sắp bay rồi đấy!' },
      { speaker: 'BXC', line: 'Dạ... em ngủ gật ạ. Em mơ thôi!' },
      { speaker: 'Nạn nhân', line: 'Mơ mà tay vẫn trong túi em?' },
    ],
    script: [
      '【0-3s | HOOK】Xe buýt đông, camera selfie POV. BXC liếc túi xách hàng xóm — text to: "Khi bạn ngồi cạnh kẻ trộm mà không biết".',
      '【3-10s】BXC chạm nhẹ túi, rút tay, lặp lại 3 lần — mỗi lần một biểu cảm "tôi vô tội" khác nhau (meme face).',
      '【10-15s】Nạn nhân quay sang, nói câu hook. BXC giả ngủ, ngáy to — cả xe buýt nhìn.',
      '【15-22s | TWIST】Slow-mo: nạn nhân lôi thẻ công an. BXC mắt trừng trừng → cắt cảnh chạy xuống xe (nhạc dramatic).',
      '【22-28s】Outro: text overlay pháp lý + logo Công an Phường Phương Liệt. Voiceover: "Để túi trước ngực. Phát hiện trộm — báo ngay."',
    ],
    role: 'Kẻ trộm "vô tri có phương pháp" — BXC khai thác tối đa biểu cảm mặt, tạo meme face nhưng không biến tội phạm thành "đáng yêu".',
    message:
      'Xe buýt, tàu điện, chợ đông người: túi xách để trước ngực, khóa kỹ, không để túi sau hoặc túi mở. Phát hiện hành vi khả nghi — báo ngay nhân viên hoặc 113.',
    cta: 'Thấy trộm trên xe công cộng → Báo tài xế/nhân viên ngay. Ghi nhớ đặc điểm, gọi 113 khi cần.',
    legalNote: 'Trộm cắp tài sản có thể bị xử lý hình sự theo Điều 173 BLHS.',
    production:
      'Quay dọc 9:16, handheld rung nhẹ tạo cảm giác thật. Nhạc trending + sound effect "whoosh" khi twist. Text overlay font to, viền đen. Quay tại xe buýt thật (xin phép).',
    sampleCaption: 'POV: Ngồi cạnh kẻ trộm trên xe buýt mà không hay biết 🚌😱 Đừng để ví bay nhé! #PhuongLietAnNinh',
    hashtags: '#BinhXangCon #PhuongLietAnNinh #DungDeViBay #CongAnPhuongPhuongLiet #TromCapXeBuyt #TuyenTruyenHai',
  },
  {
    id: 2,
    title: 'Giật Phone - Ngã Xe Hài Hước',
    subtitle: 'Cướp giật điện thoại trên đường',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'street',
    hook: 'Cướp 3 giây — ngã 5 giây 🤡',
    duration: '32 giây',
    location: 'Vỉa hè đường Giải Phóng, Phường Phương Liệt',
    mood: 'Action comedy → Fail epic → Cảnh báo pháp lý',
    viralScore: 96,
    viralLikes: '28.7K',
    viralComments: '892',
    summary:
      'Clip "fail compilation" gây nghiện: kẻ cướp giật phone chạy được đúng 3 bước thì vấp, ngã, lộn nhào — trong khi nạn nhân không hề đuổi, chỉ bình tĩnh gọi 113. Camera CCTV zoom in. Thông điệp: cướp giật không có lối thoát.',
    storyboard: [
      { time: '0:00', title: 'Mồi nhử', desc: 'Nạn nhân cầm phone mải xem TikTok trên vỉa hè.', overlay: 'Đừng mải phone khi đi đường! 📱' },
      { time: '0:04', title: 'Giật!', desc: 'BXC lao ra, slow-mo giật phone — nhạc epic.', overlay: 'Giật phone kiểu: tôi là ninja 🥷' },
      { time: '0:08', title: 'Ngã xe', desc: 'Vấp ổ gà, ngã sấp, phone bay.', overlay: 'Karma tới nhanh quá!' },
      { time: '0:15', title: 'Bình tĩnh', desc: 'Nạn nhân gọi 113, chỉ camera CCTV.', overlay: 'Không đuổi — Báo ngay 113' },
      { time: '0:25', title: 'Kết', desc: 'BXC nằm sấp, text pháp lý.', overlay: 'Cướp giật = Tự đào hố' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Đưa phone đây! Tao là... ủa, sao đường có ổ gà nhiều thế?!' },
      { speaker: 'Nạn nhân', line: 'Anh ngã xong chưa? Em gọi 113 nhé.' },
      { speaker: 'BXC', line: 'Chờ đã! Cho tao... đứng lên đã...' },
      { speaker: 'Voiceover', line: 'Cướp giật tài sản — có thể bị xử lý hình sự.' },
    ],
    script: [
      '【0-3s】Wide shot vỉa hè đông. Zoom vào người cầm phone trước mặt — text: "Lỗi phổ biến #1".',
      '【3-8s】BXC xuất hiện từ góc màn hình, slow-mo 0.5x giật phone — sound "whoosh" + nhạc dramatic.',
      '【8-14s】Chạy 3 bước → vấp → ngã lộn nhào (quay 3 góc: side, front, CCTV style). Phone bay chậm.',
      '【14-20s】Nạn nhân đứng yên, bình tĩnh bấm 113. Split screen: BXC nằm sấp / nạn nhân gọi điện.',
      '【20-32s】CCTV overlay + text pháp lý. Outro logo Công an Phường Phương Liệt.',
    ],
    role: 'Kẻ cướp "thảm hại" — physical comedy, ngã xe kiểu Jackass nhưng kết cục nghiêm: bị xử lý hình sự.',
    message:
      'Không cầm điện thoại trước mặt khi đi bộ ven đường. Bị cướp giật: ghi nhớ đặc điểm, hướng chạy, báo 113 — tuyệt đối không đuổi theo một mình.',
    cta: 'Báo 113 ngay. Cung cấp thời gian, địa điểm, mô tả đối tượng + clip camera an ninh.',
    legalNote: 'Cướp giật tài sản — Điều 175 BLHS, khung hình phạt nghiêm khắc.',
    production:
      'Slow-mo khi giật và ngã (quay 60fps). Thêm góc CCTV giả (filter xám, timestamp). Nhạc chuyển từ epic sang comedic khi ngã.',
    sampleCaption: 'Cướp phone 3 giây, ngã 5 giây 😂 Cướp giật KHÔNG có lối thoát! #GiậtPhoneNgãXe',
    hashtags: '#BinhXangCon #GiậtPhoneNgãXe #PhuongLiet113 #CuopGiậtKhongCoLoi #CongAnPhuongPhuongLiet',
  },
  {
    id: 3,
    title: 'Va Chạm Nhẹ - Nổi Cáu Lớn',
    subtitle: 'Gây rối vì va chạm giao thông nhỏ',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'traffic',
    hook: 'Xước sơn 50k — la hét 5 triệu? 🤯',
    duration: '38 giây',
    location: 'Ngã tư Phương Liệt — giờ tan tầm',
    mood: 'Căng thẳng → Hài hước quá đà → Bài học pháp lý',
    viralScore: 91,
    viralLikes: '18.2K',
    viralComments: '541',
    summary:
      'Đối lập hai thái độ sau va chạm nhẹ: một người bình tĩnh chụp ảnh, gọi bảo hiểm; BXC thì la hét, đập yên xe, chặn đường — và nhận về cái phạt lớn hơn cả tiền sửa xe.',
    storyboard: [
      { time: '0:00', title: 'Va chạm', desc: 'Hai xe máy chạm nhẹ, chỉ xước sơn.', overlay: 'Va chạm nhẹ thôi mà...' },
      { time: '0:06', title: 'Nổi điên', desc: 'BXC la hét, đập yên xe, thu hút đám đông.', overlay: 'Cáu lớn hơn va chạm!' },
      { time: '0:15', title: 'Tắc đường', desc: 'Giao thông ùn tắc, người dân quay clip.', overlay: 'Gây rối = Phạt nặng hơn' },
      { time: '0:25', title: 'Công an', desc: 'Công an đến, xử lý nhanh va chạm — phạt BXC gây rối.', overlay: 'Va chạm 5 phút. Gây rối: phạt!' },
      { time: '0:33', title: 'Kết', desc: 'BXC ngồi bệt, người kia đi uống nước.', overlay: 'Bình tĩnh = Thắng' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Anh đâm tao! Anh đâm tao! Cả phường ra mà xem!' },
      { speaker: 'Người bình tĩnh', line: 'Anh ơi, xước sơn thôi. Mình chụp ảnh, gọi bảo hiểm nhé?' },
      { speaker: 'BXC', line: 'Bảo hiểm gì! Tao đập cho anh biết tay!' },
      { speaker: 'Công an', line: 'Va chạm giải quyết xong. Anh gây rối — lập biên bản.' },
    ],
    script: [
      '【0-5s】Sound "bẹp" nhẹ — hai xe dừng. Camera quay vết xước nhỏ. Text: "Va chạm nhẹ".',
      '【5-15s】BXC nổi điên: la hét, chỉ tay, đập yên xe — timelapse đám đông tụ lại.',
      '【15-22s】Góc quay từ trên cao (ban công): giao thông tắc. Text overlay đỏ: "Gây rối trật tự công cộng".',
      '【22-30s】Công an đến, giải quyết va chạm 30 giây. Riêng BXC bị lập biên bản.',
      '【30-38s】Split: BXC ngồi bệt / người kia uống trà đá. Outro thông điệp.',
    ],
    role: 'Người "nóng như ấm trà" — diễn over-the-top, tương phản rõ với người xử lý văn minh.',
    message:
      'Va chạm giao thông: bình tĩnh, chụp ảnh hiện trường, trao đổi hoặc gọi 113. Không la hét, đập phá, chặn đường — có thể bị phạt HC hoặc truy cứu hình sự.',
    cta: 'Va chạm → Bình tĩnh, ghi hình, báo công an nếu không thỏa thuận được.',
    legalNote: 'Gây rối trật tự công cộng — Điều 318 BLHS hoặc xử phạt HC.',
    production:
      'Nhạc căng thẳng → chuyển comedic khi BXC over-react. Quay nhiều góc, thêm drone shot giả (filter).',
    sampleCaption: 'Va chạm nhẹ mà cáu như va chạm lớn 🤦 Bình tĩnh = tiết tiền! #VaChamBinhTinh',
    hashtags: '#BinhXangCon #VaChamBinhTinh #PhuongLietGiaoThong #GayRoiCongCong #CongAnPhuongPhuongLiet',
  },
  {
    id: 4,
    title: "Hàng Rong 'Chiếm' Vỉa Hè",
    subtitle: 'Lấn chiếm lòng lề đường',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'sidewalk',
    hook: 'Vỉa hè 1 mét — hàng chiếm 3 mét 🛒',
    duration: '30 giây',
    location: 'Phố nhỏ Phương Liệt — buổi sáng',
    mood: 'Đời thường → Hài nhẹ → Giải pháp tích cực',
    viralScore: 88,
    viralLikes: '9.8K',
    viralComments: '267',
    summary:
      'Before/After kinh điển: vỉa hè biến thành "chợ mini", người già và xe lăn phải xuống lòng đường. BXC hàng rong từ cãi vã → hiểu ra → dọn hàng — tạo tiếng cười nhẹ mà vẫn tôn trọng người lao động.',
    storyboard: [
      { time: '0:00', title: 'Before', desc: 'Vỉa hè chật, hàng tràn ra đường.', overlay: 'BEFORE: Vỉa hè = 0 mét 😤' },
      { time: '0:08', title: 'Phàn nàn', desc: 'Người già, mẹ bỉm phải xuống lòng đường.', overlay: 'Vỉa hè là của chung!' },
      { time: '0:14', title: 'Công an nhắc', desc: 'Giải thích quy định, không la mắng.', overlay: 'Kinh doanh OK — Đúng chỗ!' },
      { time: '0:20', title: 'After', desc: 'BXC dọn hàng, vỉa hè thông thoáng.', overlay: 'AFTER: Ai cũng vui ✅' },
      { time: '0:26', title: 'Kết', desc: 'Người dân đi bộ thoải mái.', overlay: 'Văn minh = Phát triển' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Mua đi chị ơi! Rẻ lắm! Đứng đây cho tiện!' },
      { speaker: 'Người dân', line: 'Anh ơi, nhường lối đi với. Con em đi học kìa!' },
      { speaker: 'Công an', line: 'Anh kinh doanh được, nhưng đúng quy định. Vỉa hè để người đi bộ.' },
      { speaker: 'BXC', line: 'Dạ em hiểu rồi ạ. Em dọn ngay!' },
    ],
    script: [
      '【0-5s】Split-screen Before: vỉa hè kín, người chen chúc. Loa kẹo kéo BXC.',
      '【5-12s】Người già, xe lăn không lọt — phải xuống lòng đường. Text cảnh báo đỏ.',
      '【12-18s】Công an đến, giải thích nhẹ nhàng. BXC ban đầu cãi, mặt "bất bình".',
      '【18-25s】Transition swipe: After — hàng gọn, vỉa hè rộng. Người dân thumbs up.',
      '【25-30s】Outro: "Kinh doanh có trật tự — cộng đồng hài lòng".',
    ],
    role: 'Hàng rong "ban đầu cứng, sau mềm" — tôn trọng người lao động, không chế giễu nghề.',
    message: 'Không lấn chiếm vỉa hè, lòng đường. Kinh doanh có trật tự = an toàn + văn minh + bền vững.',
    cta: 'Phản ánh lấn chiếm hè phố → Hotline Công an Phường Phương Liệt.',
    legalNote: 'Lấn chiếm lòng đường, vỉa hè — xử phạt HC theo NĐ 168/2024.',
    production: 'Split-screen Before/After với transition wipe. Nhạc vui, tempo nhanh. Quay phố thật.',
    sampleCaption: 'Vỉa hè 1 mét mà chiếm 3 mét 🛒 Before/After này mới đã! #ViaHeKhongPhaiRiengAi',
    hashtags: '#BinhXangCon #ViaHeKhongPhaiRiengAi #PhuongLietVanMinh #LanChiemViaHe #CongAnPhuongPhuongLiet',
  },
  {
    id: 5,
    title: 'Cá Độ Thua Sạch - Trộm Để Gỡ',
    subtitle: 'Hệ lụy cờ bạc, cá độ',
    category: 'ca-do',
    categoryLabel: 'Cá độ & Cờ bạc',
    scene: 'drama',
    hook: 'Thua cá độ → Nợ 47 triệu → Trộm xe? 💸',
    duration: '35 giây',
    location: 'Quán nước vỉa hè Phương Liệt',
    mood: 'Drama → Hài đen → Cảnh báo nghiêm',
    viralScore: 93,
    viralLikes: '22.1K',
    viralComments: '743',
    summary:
      'Câu chuyện "domino tội phạm" trong 35 giây: thua cá độ → nợ chồng nợ → bạn rủ trộm xe gỡ → BXC đồng ý (mặt "tỉ táo") → công an xuất hiện đúng lúc. Một clip, ba tội danh.',
    storyboard: [
      { time: '0:00', title: 'Thua cá độ', desc: 'BXC xem kết quả, mặt tái mét.', overlay: 'Thua sạch... 47 triệu 💀' },
      { time: '0:08', title: 'Rủ trộm', desc: 'Bạn thì thầm "trộm xe kia gỡ đi".', overlay: 'Cá độ → Nợ → Phạm pháp' },
      { time: '0:15', title: 'Hành động', desc: 'BXC rút chìa, tay run — nhạc căng.', overlay: 'Đừng đi con đường này!' },
      { time: '0:22', title: 'Bị bắt', desc: 'Công an tuần tra — BXC đứng hình.', overlay: 'Plot twist: Công an đến 👮' },
      { time: '0:30', title: 'Kết', desc: 'Text pháp lý cá độ + trộm cắp.', overlay: 'Cá độ = Con đường chết' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Thua hết rồi... 47 triệu... Sao giờ này đây...' },
      { speaker: 'Bạn', line: 'Trộm cái xe kia đi. Gỡ xong trả nợ. 5 phút thôi!' },
      { speaker: 'BXC', line: 'Nhưng mà... ủa, sao có công an ở đây?!' },
      { speaker: 'Công an', line: 'Anh vừa nói gì? Và cái chìa khoa trong tay anh là gì?' },
    ],
    script: [
      '【0-5s】Close-up mặt BXC, phone hiện "THUA -47.000.000đ". Nhạc dramatic.',
      '【5-12s】Bạn rủ trộm — BXC do dự, mặt "suy tính" hài hước. Text: "Domino tội phạm".',
      '【12-20s】BXC tiến tới xe máy, tay run rút chìa — camera rung theo.',
      '【20-28s】Đèn flash công an. BXC quay lại — freeze frame + zoom mặt.',
      '【28-35s】Text pháp lý: cá độ trái phép + trộm cắp. Hotline tư vấn.',
    ],
    role: 'Người sa vào nợ nần — biểu cảm "tỉ táo" khi quyết định phạm pháp, kết cục không may mắn.',
    message: 'Cá độ, cờ bạc trái phép = vi phạm pháp luật. Dễ dẫn đến nợ nần, gian lận, trộm cắp. Không tham gia, không tổ chức.',
    cta: 'Phát hiện tụ cá độ → Tố giác Công an Phường Phương Liệt ngay.',
    legalNote: 'Cá độ trái phép — Điều 321-322 BLHS. Trộm cắp — Điều 173 BLHS.',
    production: 'Dramatic zoom + filter tối. Số nợ hiện trên phone (prop). Nhạc chuyển từ tense sang "fail sound".',
    sampleCaption: 'Thua cá độ 47 triệu rồi muốn trộm xe gỡ? 💸 Đừng! #CaDoLaConDuongChet',
    hashtags: '#BinhXangCon #CaDoLaConDuongChet #PhuongLietKhongCoBac #CoBacTráiPhep #CongAnPhuongPhuongLiet',
  },
  {
    id: 6,
    title: 'Kẻ Lạ Theo Dõi - Báo Ngay Công An',
    subtitle: 'Cảnh giác an toàn cá nhân',
    category: 'to-giac',
    categoryLabel: 'Tố giác & Cảnh giác',
    scene: 'night',
    hook: 'Theo sau 200m — Đừng im lặng! 🌙',
    duration: '40 giây',
    location: 'Ngõ nhỏ Phương Liệt — buổi tối',
    mood: 'Hồi hộp → Twist hài → Bài học an toàn',
    viralScore: 90,
    viralLikes: '15.6K',
    viralComments: '428',
    summary:
      'Thriller mini 40 giây: phụ nữ đi về nhà, BXC bám theo — căng thẳng từng giây. Cô vào tiệm tạp hóa, gọi 113. Twist: BXC đi nhầm ngõ. Thông điệp vẫn đúng 100%: ưu tiên an toàn.',
    storyboard: [
      { time: '0:00', title: 'Đi về', desc: 'Phụ nữ đi bộ, đèn đường mờ.', overlay: '9PM — Đi nhà một mình' },
      { time: '0:08', title: 'Bám theo', desc: 'BXC đi sau 5 mét, nhạc hồi hộp.', overlay: 'Cảm thấy không an toàn?' },
      { time: '0:18', title: 'Hành động đúng', desc: 'Vào tiệm đông người, nhờ gọi 113.', overlay: 'Vào nơi đông người — Báo ngay!' },
      { time: '0:28', title: 'Twist', desc: 'BXC: "Em đi nhầm ngõ ạ!"', overlay: 'Plot twist: Nhầm đường 😅' },
      { time: '0:35', title: 'Kết', desc: 'Dù nhầm hay thật — luôn ưu tiên an toàn.', overlay: 'An toàn > Ngại ngần' },
    ],
    dialogues: [
      { speaker: 'Phụ nữ', line: 'Sao người này theo mình hoài vậy...' },
      { speaker: 'Chủ quán', line: 'Chị yên tâm. Em gọi công an ngay.' },
      { speaker: 'BXC', line: 'Dạ em xin lỗi! Em đi nhầm ngõ, tìm nhà bạn...' },
      { speaker: 'Voiceover', line: 'Cảm thấy nguy hiểm — đừng im lặng. Gọi 113.' },
    ],
    script: [
      '【0-5s】POV đi bộ buổi tối, nhạc suspense. Text: "9PM — Đi nhà một mình".',
      '【5-15s】Góc sau: BXC bám theo. Phụ nữ quay lại nhìn — tăng tốc.',
      '【15-25s】Cô vào tiệm tạp hóa, chủ quán gọi 113. Camera handheld rung.',
      '【25-33s | TWIST】BXC xin lỗi, chỉ map trên phone "đi nhầm". Cả tiệm cười nhẹ.',
      '【33-40s】Thông điệp: dù nhầm hay thật — luôn ưu tiên an toàn.',
    ],
    role: 'Kẻ "đáng ngờ" — tạo suspense, twist hài không làm giảm thông điệp cảnh giác.',
    message: 'Đi đường muộn: chọn đường sáng, tránh ngõ vắng. Tin cảm giác nguy hiểm — vào nơi đông người, báo 113.',
    cta: 'Nguy hiểm cấp bách → Gọi 113. Mô tả người, phương tiện, hướng di chuyển.',
    legalNote: 'Theo dõi, quấy rối có thể bị xử lý theo Điều 286 BLHS.',
    production: 'Ánh sáng đèn đường, không quá đáng sợ. Nhạc suspense → relief khi twist. POV + góc thứ 3.',
    sampleCaption: 'Theo sau 200m mà im lặng? Đừng! 🌙 #BaoNgay113 #PhuongLietAnToan',
    hashtags: '#BinhXangCon #BaoNgay113 #PhuongLietAnToan #CanhGiacCaNhan #CongAnPhuongPhuongLiet',
  },
  {
    id: 7,
    title: "Va Chạm 'Tình Cờ' - Móc Túi Tinh Vi",
    subtitle: 'Trộm cắp tinh vi tại chợ đông người',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'market',
    hook: 'Xin lỗi 180 lần — Móc túi 1 lần 🎭',
    duration: '30 giây',
    location: 'Chợ Phương Liệt — sáng cuối tuần',
    mood: 'Split-screen thriller → Bắt quả tang → Cảnh báo',
    viralScore: 95,
    viralLikes: '19.4K',
    viralComments: '612',
    summary:
      'Masterclass móc túi: mặt cười xin lỗi liên tục, tay móc túi không ngừng — split-screen cho thấy "hai mặt" của kẻ trộm. Bị bắt quả tang nhờ người bán hàng cảnh giác.',
    storyboard: [
      { time: '0:00', title: 'Chợ đông', desc: 'Đông người, ồn ào.', overlay: 'Chợ đông = Cơ hội trộm?' },
      { time: '0:05', title: 'Va chạm', desc: 'BXC "vô tình" va vào nạn nhân.', overlay: 'Va chạm tình cờ...' },
      { time: '0:12', title: 'Split-screen', desc: 'Mặt cười / Tay móc túi.', overlay: 'Xin lỗi 180 lần 🎭' },
      { time: '0:20', title: 'Bắt quả tang', desc: 'Người bán hét "Có trộm!"', overlay: 'Móc túi có chủ!' },
      { time: '0:26', title: 'Kết', desc: 'Cảnh báo + camera an ninh.', overlay: 'Để túi trước ngực!' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Dạ em xin lỗi chị! Em xin lỗi! Em lỡ tay! Em xin lỗi lần nữa!' },
      { speaker: 'Người bán', line: 'Có trộm! Tay anh trong túi người ta kìa!' },
      { speaker: 'BXC', line: 'Không phải! Em... em tìm hộp quẹt thôi!' },
      { speaker: 'Đám đông', line: 'Giơ hai tay ra! Camera kia kìa!' },
    ],
    script: [
      '【0-4s】Wide shot chợ đông. Zoom BXC len lỏi giữa đám đông.',
      '【4-10s】Va chạm nhẹ — BXC xin lỗi liên tục, không ngừng.',
      '【10-18s | SPLIT】Trái: mặt cười. Phải: tay móc túi. Text: "Hai mặt".',
      '【18-24s】Người bán hét. Đám đông vây. BXC giơ tay — ví rơi.',
      '【24-30s】CCTV overlay + cảnh báo: túi trước ngực, khóa kỹ.',
    ],
    role: 'Kẻ móc túi "diplomat" — đôi mặt rõ ràng, hài nhưng đáng sợ.',
    message: 'Chợ, siêu thị, sự kiện đông: túi trước ngực, khóa kỹ. Va chạm cố ý → kiểm tra tài sản ngay.',
    cta: 'Mất trộm tại chợ → Báo ban quản lý + Công an. Cung cấp clip camera.',
    legalNote: 'Trộm cắp tài sản — Điều 173 BLHS.',
    production: 'Split-screen mặt/tay là điểm nhấn. Handheld, chợ thật. Sound "ding" khi bắt quả tang.',
    sampleCaption: 'Xin lỗi 180 lần, móc túi 1 lần 🎭 Split-screen này đỉnh! #MocTuiTinhVi',
    hashtags: '#BinhXangCon #MocTuiTinhVi #ChoPhuongLiet #CanhGiacChoDong #CongAnPhuongPhuongLiet',
  },
  {
    id: 8,
    title: 'Đánh Bài Quán Cà Phê - Bị Bắt Quả Tang',
    subtitle: 'Tụ điểm cờ bạc công cộng',
    category: 'ca-do',
    categoryLabel: 'Cá độ & Cờ bạc',
    scene: 'cards',
    hook: 'Ảo thuật gia hết thuốc — Bị bắt quả tang 🃏',
    duration: '34 giây',
    location: 'Quán cà phê vỉa hè Phương Liệt',
    mood: 'Comedy crime → Bắt quả tang → Pháp lý',
    viralScore: 89,
    viralLikes: '11.3K',
    viralComments: '334',
    summary:
      'BXC "ảo thuật gia" rút bài từ tay áo giữa ván bài ăn tiền — bị lộ, cãi nhau hài, rồi công an ập vào. Một clip dạy luôn: bài không phải trò chơi, là vi phạm.',
    storyboard: [
      { time: '0:00', title: 'Ván bài', desc: '4 người, tiền trên bàn.', overlay: 'Chơi bài ăn tiền = Vi phạm!' },
      { time: '0:08', title: 'Gian lận', desc: 'BXC rút bài từ tay áo.', overlay: 'Ảo thuật gia BXC 🎩' },
      { time: '0:15', title: 'Lộ diện', desc: 'Bị phát hiện, cãi vã hài.', overlay: 'Bị bắt quả tang!' },
      { time: '0:22', title: 'Công an', desc: 'Kiểm tra, thu bài tiền (prop).', overlay: 'Công an vào kiểm tra 👮' },
      { time: '0:30', title: 'Kết', desc: 'BXC viết cam kết — meme face.', overlay: 'Cờ bạc = Hình sự' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Tôi bị oan! Bài tự nhiên... bay vào tay áo tôi!' },
      { speaker: 'Bạn chơi', line: 'Bay vào tay áo? Anh tưởng tôi mù à?!' },
      { speaker: 'Công an', line: 'Đánh bài ăn tiền tại nơi công cộng — lập biên bản.' },
      { speaker: 'BXC', line: 'Dạ... em viết cam kết ạ... (mặt meme)' },
    ],
    script: [
      '【0-5s】Góc trên xuống bàn bài, tiền prop. Text: "Tụ điểm cờ bạc mini".',
      '【5-12s】BXC rút bài từ tay áo — slow-mo, nhạc magic.',
      '【12-18s】Bị phát hiện. Cãi vã hài — "bay vào tay áo".',
      '【18-26s】Công an vào. Thu bài, tiền. BXC ngồi góc viết cam kết.',
      '【26-34s】Text pháp lý cờ bạc. Outro logo.',
    ],
    role: 'Ảo thuật gia thất bại — comedy peak rồi kết nghiêm.',
    message: 'Đánh bài ăn tiền tại quán công cộng = cờ bạc trái phép. Tổ chức và tham gia đều bị xử lý.',
    cta: 'Phát hiện tụ cờ bạc → Tố giác ẩn danh hoặc trực tiếp tại trụ sở.',
    legalNote: 'Đánh bạc — Điều 321-322 BLHS.',
    production: 'Góc top-down bàn bài. Slow-mo rút bài. Prop tiền giấy. Xin phép chủ quán.',
    sampleCaption: 'Ảo thuật gia rút bài từ tay áo 🃏 Bị bắt quả tang! #CoBacKhongVui',
    hashtags: '#BinhXangCon #CoBacKhongVui #PhuongLiet113 #DanhBaiAnTien #CongAnPhuongPhuongLiet',
  },
  {
    id: 9,
    title: "Say Xỉn Gây Rối - 'Ngáo' Giữa Đường Phố",
    subtitle: 'Gây rối trật tự khi say rượu',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'night',
    hook: 'Say ≠ Được phép ngáo giữa đường 🍺',
    duration: '36 giây',
    location: 'Lòng đường Phương Liệt — đêm cuối tuần',
    mood: 'Party fail → Gây rối → Xử lý pháp lý',
    viralScore: 92,
    viralLikes: '24.5K',
    viralComments: '891',
    summary:
      'BXC say xỉn đứng giữa lòng đường hát karaoke không mic, chắn xe, nhảy múa — bạn bè kéo không nổi. Công an đến, đưa về an toàn. Clip vui nhưng thông điệp cứng: say không phải giấy phép gây rối.',
    storyboard: [
      { time: '0:00', title: 'Say xỉn', desc: 'BXC đứng giữa đường, hát to.', overlay: 'Say xỉn + Giữa đường = 🚨' },
      { time: '0:08', title: 'Chắn xe', desc: 'Xe bấm còi, BXC vẫn nhảy.', overlay: 'Say ≠ Được phép gây rối!' },
      { time: '0:16', title: 'Kéo không nổi', desc: 'Bạn bè 3 người kéo, BXC vẫn hát.', overlay: '3 vs 1 — BXC thắng 😂' },
      { time: '0:24', title: 'Công an', desc: 'Đến xử lý, đưa về an toàn.', overlay: 'Gọi 113 — Đừng đối đầu' },
      { time: '0:32', title: 'Kết', desc: 'BXC ngủ gật trên xe công an.', overlay: 'Uống có trách nhiệm' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Tôi là... tôi là... ngôi sao đường phố! Cho tôi mic!' },
      { speaker: 'Bạn bè', line: 'Về thôi! Xe còi kìa! Công an tới rồi!' },
      { speaker: 'BXC', line: 'Một bài nữa thôi! *hát to*' },
      { speaker: 'Công an', line: 'Anh về nhà nghỉ. Say rượu gây rối — em nhắc nhở anh nhé.' },
    ],
    script: [
      '【0-5s】Đêm cuối tuần, BXC giữa lòng đường hát. Text: "Say xỉn + Giữa đường".',
      '【5-12s】Xe máy, ô tô bấm còi. BXC nhảy múa, không nhường.',
      '【12-20s】3 bạn kéo — BXC vẫn hát. Comedy physical.',
      '【20-28s】Công an đến, nhẹ nhàng đưa lên xe. BXC ngủ gật (hài).',
      '【28-36s】Thông điệp: không lái xe khi say, không gây rối.',
    ],
    role: 'Người say "ngáo" — physical comedy, hậu quả phiền phức cho bản thân và cộng đồng.',
    message: 'Say rượu không được gây rối, chắn đường, đánh nhau. Vi phạm → phạt HC hoặc hình sự.',
    cta: 'Gặp người say gây rối → Gọi 113, không đối đầu một mình.',
    legalNote: 'Gây rối trật tự — Điều 318 BLHS. Lái xe khi say — Điều 260 BLHS.',
    production: 'Quay ban đêm an toàn. Nhạc karaoke lạc tune. Comedy physical khi kéo.',
    sampleCaption: 'Say xỉn hát giữa đường — 3 người kéo không nổi 🍺😂 #SayKhongGayRoi',
    hashtags: '#BinhXangCon #SayKhongGayRoi #PhuongLietDemAnToan #GayRoiCongCong #CongAnPhuongPhuongLiet',
  },
  {
    id: 10,
    title: 'Thấy Mà Im - Hối Hận Muộn Màng',
    subtitle: 'Tố giác tội phạm — trách nhiệm cộng đồng',
    category: 'to-giac',
    categoryLabel: 'Tố giác & Cảnh giác',
    scene: 'home',
    hook: 'Hôm nay im lặng — Ngày mai nhà mình 🏠',
    duration: '42 giây',
    location: 'Khu tập thể Phương Liệt',
    mood: 'Emotional → Twist cá nhân → Call to action mạnh',
    viralScore: 97,
    viralLikes: '31.2K',
    viralComments: '1.1K',
    summary:
      'Clip cảm xúc nhất bộ: BXC thấy trộm xe hàng xóm — quay đi làm ngơ. 3 ngày sau, nhà mình bị đột nhập. Mặt "trăm ngàn lỗi lầm". Chạy đến Công an tố giác. Thông điệp: im lặng = dung túng tội phạm.',
    storyboard: [
      { time: '0:00', title: 'Chứng kiến', desc: 'BXC ban công, thấy trộm xe hàng xóm.', overlay: 'Thấy mà... im lặng? 😶' },
      { time: '0:10', title: 'Làm ngơ', desc: 'Quay đi, giả vờ không thấy.', overlay: 'Không muốn dính líu' },
      { time: '0:18', title: '3 ngày sau', desc: 'Nhà BXC bị đột nhập — đồ đạc lộn xộn.', overlay: 'Hôm nay im — Ngày mai là mình' },
      { time: '0:30', title: 'Hối hận', desc: 'BXC chạy đến Công an Phường Phương Liệt.', overlay: 'Thấy mà báo — Ngay!' },
      { time: '0:38', title: 'Kết', desc: 'Hotline tố giác + cam kết.', overlay: 'Cùng nhau an toàn 💙' },
    ],
    dialogues: [
      { speaker: 'BXC (VO)', line: 'Hôm qua trộm nhà người ta, tôi im lặng. Hôm nay... nhà tôi.' },
      { speaker: 'BXC', line: 'Sao tôi không báo hôm đó... Giờ muộn rồi...' },
      { speaker: 'Công an', line: 'Anh tố giác là đúng. Lần sau thấy gì — báo ngay, bảo vệ cả hàng xóm.' },
      { speaker: 'BXC', line: 'Em hứa. Lần sau em không im nữa!' },
    ],
    script: [
      '【0-5s】BXC ban công, nhìn kẻ trộm xe hàng xóm. Text: "Thấy mà im lặng?".',
      '【5-12s】Quay đi, nhún vai "không liên quan". Nhạc buồn nhẹ.',
      '【12-22s | TIME JUMP】"3 ngày sau" — BXC mở cửa, nhà lộn xộn. Freeze face.',
      '【22-32s】BXC chạy đến trụ sở Công an Phường Phương Liệt. Cảm xúc thật.',
      '【32-42s】Hotline tố giác. Text: "Im lặng = Dung túng. Thấy mà báo."',
    ],
    role: 'Người chứng kiến thờ ơ — arc cảm xúc từ indifferent → hối hận → hành động.',
    message: 'Tố giác tội phạm = quyền và trách nhiệm công dân. Im lặng giúp tội phạm tái phạm, gây hại cả cộng đồng.',
    cta: 'Thấy khả nghi → Gọi 113 hoặc hotline Công an Phường Phương Liệt. Có thể tố giác ẩn danh.',
    legalNote: 'Không tố giác không phạm tội, nhưng tố giác là trách nhiệm công dân.',
    production: 'Nhạc emotional piano. Time jump "3 ngày sau" với hiệu ứng date stamp. Cảnh cảm xúc thật.',
    sampleCaption: 'Thấy trộm mà im lặng... 3 ngày sau nhà mình 😢 Đừng lặp lại! #ThayMaBao',
    hashtags: '#BinhXangCon #ThayMaBao #PhuongLietCungNhau #ToGiacToiPham #CongAnPhuongPhuongLiet',
  },
];