const PROJECT_AUTHOR = 'Bach Truong';

/** Văn bản pháp luật CHXHCNVN — căn cứ kịch bản tuyên truyền */
const LAW_REF = {
  BLHS: 'Bộ luật Hình sự số 100/2015/QH13 (BLHS 2015)',
  BLTTHS: 'Bộ luật Tố tụng hình sự số 101/2015/QH13',
  HP: 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013',
  ND168: 'Nghị định 168/2024/NĐ-CP',
  LTATGT: 'Luật Trật tự, an toàn giao thông đường bộ',
};

const CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: '✨' },
  { id: 'trom-cap', label: 'Trộm cắp & Cướp giật', icon: '🚨' },
  { id: 'gay-roi', label: 'Gây rối trật tự công cộng', icon: '⚠️' },
  { id: 'ca-do', label: 'Cá độ & Cờ bạc', icon: '🎲' },
  { id: 'to-giac', label: 'Tố giác & Cảnh giác', icon: '👁️' },
];

const CONTENT_ITEMS = [
  {
    id: 1,
    title: 'Ví Ơi Đừng Bay',
    subtitle: 'Trộm Cắp Trên Xe Buýt',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'bus',
    hook: 'Tay trong túi — mà bảo "đang ngủ gật"? Cả xe buýt quay lại nhìn 😳',
    duration: '30 giây',
    location: 'Tuyến xe buýt 08 Phương Liệt — giờ cao điểm 7h30',
    mood: 'Cringe comedy → Meme face → Twist đứng hình → Outro pháp lý',
    viralScore: 97,
    viralLikes: '47.8K',
    viralComments: '1.2K',
    summary:
      'Clip "POV kẻ trộm trên xe buýt" gây nghiện toàn quốc: BXC ngồi cạnh hành khách, mắt dán vào túi xách mở như đang đọc đề thi đại học. Mỗi lần chạm túi là một lần diễn "tôi vô tội" — ngáy to, nhắm mắt, giả ngủ gật. Cú twist: nạn nhân lôi thẻ Công an, BXC đứng hình 3 giây rồi nhảy xuống xe — cả hành khách vỗ tay. Một clip, một câu nhớ mãi: Đừng để ví bay.',
    storyboard: [
      { time: '0:00', title: 'Hook viral 3s', desc: 'POV selfie: BXC liếc túi xách mở bên cạnh, nhạc "Oh No" trending bật full.', overlay: 'POV: Bạn ngồi cạnh kẻ trộm mà không biết 🚌' },
      { time: '0:06', title: 'Móc túi kiểu meme', desc: 'Tay lén chạm túi 3 lần — mỗi lần một meme face khác: vô tội, ngáy, nhắm mắt.', overlay: 'Tôi chỉ... kiểm tra khóa thôi mà! 🙄' },
      { time: '0:13', title: 'Câu thoại bắt trend', desc: 'Nạn nhân quay sang, nhìn thẳng camera. Cả xe im lặng.', overlay: 'Ví em sắp bay rồi đấy anh! ✈️' },
      { time: '0:20', title: 'Plot twist đứng hình', desc: 'Slow-mo: nạn nhân lôi thẻ Công an. BXC mắt trừng → freeze 2s → nhảy xuống xe.', overlay: 'Plot twist: Chị là Công an 👮‍♀️' },
      { time: '0:26', title: 'Outro pháp lý', desc: 'Text Điều 173 full màn + logo Công an Phường Phương Liệt. Voiceover trích điều luật.', overlay: 'Trộm ví xe buýt = Hình sự · Điều 173 BLHS', legalOutro: 'Điều 173 BLHS 2015 · Khoản 1' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Chị ơi, túi chị không khóa à? Em... em lo an toàn cho chị thôi ạ!' },
      { speaker: 'Nạn nhân', line: 'Anh kiểm tra lâu thế. Ví em sắp bay rồi đấy — cả xe buýt nhìn anh kìa!' },
      { speaker: 'BXC', line: 'Dạ... em ngủ gật ạ. Em mơ thôi! Tay em tự chạy vào túi chị!' },
      { speaker: 'Nạn nhân', line: 'Mơ mà tay vẫn móc ví em? Anh đứng lại đây.' },
      { speaker: 'Voiceover', line: 'Trộm cắp tài sản trên xe buýt — Điều 173 BLHS 2015 Khoản 1: phạt tù từ 06 tháng đến 03 năm. Túi trước ngực, khóa kỹ — báo 113.' },
    ],
    script: [
      '【0-3s | HOOK】Xe buýt đông kín, camera selfie POV rung nhẹ. BXC liếc túi xách hàng xóm — text to đỏ: "Khi bạn ngồi cạnh kẻ trộm mà không biết". Sound "ding" viral.',
      '【3-11s | ACTION】BXC chạm nhẹ túi, rút tay, lặp 3 lần — mỗi lần một biểu cảm meme khác (vô tội → ngáy → nhắm mắt). Split-screen: mặt BXC / tay trong túi.',
      '【11-17s | DIALOGUE】Nạn nhân quay sang, nói câu hook. BXC giả ngủ gật, ngáy to — cả xe buýt quay lại nhìn, một người quay clip.',
      '【17-24s | TWIST】Slow-mo 0.3x: nạn nhân lôi thẻ Công an. BXC mắt trừng trừng → freeze frame 2 giây → cắt cảnh chạy xuống xe (nhạc dramatic + tiếng còi xe buýt).',
      '【24-30s | OUTRO | Điều 173 Khoản 1】Text overlay full: "Điều 173 BLHS 2015 — Tội trộm cắp tài sản (Khoản 1): tù 06 tháng – 03 năm". Logo Công an Phường Phương Liệt. Voiceover: "Túi trước ngực — khóa kỹ — báo 113 ngay."',
    ],
    role: 'Kẻ trộm "vô tri có phương pháp" — BXC khai thác tối đa biểu cảm meme face, tạo moment shareable nhưng không biến tội phạm thành "đáng yêu".',
    message:
      'Xe buýt, tàu điện, BRT: túi xách để trước ngực, khóa kỹ, không để túi sau hoặc túi mở. Phát hiện hành vi khả nghi — báo tài xế, nhân viên hoặc 113 ngay. Đừng để ví bay vì 3 giây mất cảnh giác.',
    cta: 'Thấy trộm trên xe công cộng → Báo tài xế/nhân viên ngay. Ghi nhớ đặc điểm, hướng chạy, gọi 113. Cung cấp clip nếu có.',
    legalNote:
      'Trộm ví, điện thoại trên xe buýt thuộc tội trộm cắp tài sản — Điều 173 BLHS 2015, Khoản 1. Tài sản từ 2.000.000 đến dưới 50.000.000 đồng: phạt tù 06 tháng – 03 năm hoặc cải tạo không giam giữ đến 03 năm. Dưới 2 triệu kèm tình tiết tăng nặng vẫn bị xử lý.',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 173',
        name: 'Tội trộm cắp tài sản',
        clause: 'Khoản 1',
        text: 'Người nào trộm cắp tài sản của người khác có giá trị từ 2.000.000 đồng đến dưới 50.000.000 đồng (hoặc dưới 2.000.000 đồng kèm tình tiết tăng nặng), thì bị phạt cải tạo không giam giữ đến 03 năm hoặc phạt tù từ 06 tháng đến 03 năm.',
        penalty: 'Cải tạo không giam giữ đến 03 năm hoặc tù 06 tháng – 03 năm',
        applies: 'Móc túi, trộm ví, điện thoại trên xe buýt, tàu điện, phương tiện công cộng',
      },
    ],
    production:
      'Quay dọc 9:16, handheld rung nhẹ kiểu POV TikTok. Split-screen mặt/tay ở giữa clip. Outro bắt buộc text: "Điều 173 BLHS 2015 — Tội trộm cắp tài sản · Khoản 1". Quay tại xe buýt thật (xin phép). Freeze frame 2s khi twist.',
    sampleCaption: 'Tay trong túi mà bảo ngủ gật? Cả xe buýt nhìn anh 😳 Điều 173 BLHS K1 không cười! #DungDeViBay #Dieu173',
    hashtags: '#BinhXangCon #PhuongLietAnNinh #DungDeViBay #CongAnPhuongPhuongLiet #Dieu173BLHS #TuyenTruyenHai #XeBuytAnToan',
  },
  {
    id: 2,
    title: 'Giật Phone - Ngã Xe Hài Hước',
    subtitle: 'Cướp giật điện thoại trên đường',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'street',
    hook: 'Cướp 3 giây — ngã 5 giây — karma không delay 🤡📱',
    duration: '34 giây',
    location: 'Vỉa hè đường Giải Phóng, Phường Phương Liệt — gần camera CCTV',
    mood: 'Action comedy → Fail epic Jackass → Bình tĩnh gọi 113 → Outro pháp lý',
    viralScore: 98,
    viralLikes: '89.3K',
    viralComments: '2.4K',
    summary:
      'Fail compilation huyền thoại Phương Liệt: BXC lao ra giật phone slow-mo kiểu ninja — chạy đúng 3 bước thì vấp ổ gà, ngã lộn nhào, phone bay vòng vòng. Trong khi nạn nhân KHÔNG đuổi, chỉ bình tĩnh bấm 113 và chỉ camera CCTV. Split-screen: BXC nằm sấp / nạn nhân gọi điện. Karma instant, Điều 171 không đùa — cướp giật nghiêm hơn trộm cắp gấp đôi.',
    storyboard: [
      { time: '0:00', title: 'Mồi nhử phổ biến', desc: 'Nạn nhân cầm phone trước mặt, mải xem TikTok trên vỉa hè đông.', overlay: 'Lỗi #1: Mải phone khi đi đường 📱' },
      { time: '0:05', title: 'Giật slow-mo', desc: 'BXC lao từ góc màn hình, slow-mo 0.3x giật phone — nhạc epic + whoosh.', overlay: 'Giật phone kiểu: tôi là ninja 🥷' },
      { time: '0:10', title: 'Karma instant', desc: 'Chạy 3 bước → vấp ổ gà → ngã lộn nhào. Phone bay chậm. Quay 3 góc: side, front, CCTV.', overlay: 'Karma tới nhanh hơn 4G! ⚡' },
      { time: '0:18', title: 'Bình tĩnh thắng', desc: 'Nạn nhân đứng yên, bấm 113, chỉ camera. BXC nằm sấp vẫn cố đứng dậy.', overlay: 'Không đuổi — Báo 113 ngay ☎️' },
      { time: '0:28', title: 'Outro pháp lý', desc: 'CCTV overlay zoom BXC + text Điều 171 full. Logo Công an Phường Phương Liệt.', overlay: 'Cướp giật = Tự đào hố · Điều 171 BLHS', legalOutro: 'Điều 171 BLHS 2015 · Khoản 1' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Đưa phone đây! Tao là ninja đường phố — ủa, sao đường Phương Liệt ổ gà nhiều thế?!' },
      { speaker: 'Nạn nhân', line: 'Anh ngã xong chưa? Em không đuổi đâu. Em gọi 113 và chỉ camera kia kìa.' },
      { speaker: 'BXC', line: 'Chờ đã! Cho tao... đứng lên đã... Phone bay đâu rồi?!' },
      { speaker: 'Người qua đường', line: 'Anh nằm yên đi! Camera quay hết rồi! Công an tới rồi!' },
      { speaker: 'Voiceover', line: 'Cướp giật tài sản bất ngờ — Điều 171 BLHS 2015 Khoản 1: phạt tù từ 01 đến 05 năm. Không phải Điều 175. Báo 113, cung cấp clip CCTV.' },
    ],
    script: [
      '【0-3s | HOOK】Wide shot vỉa hè đông Giải Phóng. Zoom vào người cầm phone trước mặt — text đỏ: "Lỗi phổ biến #1 khi đi đường".',
      '【3-9s | ACTION】BXC xuất hiện từ góc màn hình, slow-mo 0.3x giật phone — sound "whoosh" + nhạc epic. Text: "Cướp 3 giây".',
      '【9-16s | FAIL】Chạy 3 bước → vấp ổ gà → ngã lộn nhào (3 góc: side, front, CCTV style). Phone bay slow-mo. Text: "Ngã 5 giây". Tiếng "oof" meme.',
      '【16-24s | CALM】Split screen: BXC nằm sấp cố đứng / nạn nhân bình tĩnh bấm 113, chỉ camera. Text: "Không đuổi — Báo ngay".',
      '【24-34s | OUTRO | Điều 171 Khoản 1】CCTV overlay zoom BXC + text: "Điều 171 BLHS 2015 — Tội cướp giật tài sản (Khoản 1): tù 01–05 năm — KHÔNG phải Điều 175". Logo Công an Phường Phương Liệt. Voiceover trích điều luật.',
    ],
    role: 'Kẻ cướp "thảm hại có học thuyết" — physical comedy kiểu Jackass, ngã xe epic nhưng kết cục nghiêm: bị xử lý hình sự Điều 171.',
    message:
      'Không cầm điện thoại trước mặt khi đi bộ ven đường — đặc biệt vỉa hè đông, gần ổ gà. Bị cướp giật: ghi nhớ đặc điểm, hướng chạy, báo 113 — tuyệt đối không đuổi theo một mình. Cung cấp clip CCTV nếu có.',
    cta: 'Báo 113 ngay. Cung cấp thời gian, địa điểm, mô tả đối tượng (áo, tóc, chiều cao) + clip camera an ninh gần nhất.',
    legalNote:
      'Giật điện thoại trên đường thuộc tội cướp giật tài sản — Điều 171 BLHS 2015, Khoản 1 (KHÔNG phải Điều 175). Dùng sức mạnh, đe dọa hoặc bất ngờ giật tài sản trị giá từ 2–50 triệu: phạt tù từ 01 đến 05 năm — nghiêm hơn trộm cắp thông thường (Điều 173).',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 171',
        name: 'Tội cướp giật tài sản',
        clause: 'Khoản 1',
        text: 'Người nào dùng sức mạnh, đe dọa dùng sức mạnh ngay tại chỗ hoặc bất ngờ đánh người có tài sản giật lấy tài sản, hoặc cướp giật tài sản trị giá từ 2.000.000 đến dưới 50.000.000 đồng, thì bị phạt tù từ 01 đến 05 năm.',
        penalty: 'Phạt tù từ 01 đến 05 năm',
        applies: 'Giật điện thoại, túi xách, dây chuyền, balo trên vỉa hè, đường phố Phương Liệt',
      },
    ],
    production:
      'Slow-mo 60fps + góc CCTV giả (filter xanh). Split-screen BXC/nạn nhân. Quay 3 góc ngã. Outro bắt buộc: "Điều 171 BLHS 2015 — Tội cướp giật tài sản · Khoản 1 (KHÔNG phải Điều 175)". Sound "oof" meme khi ngã.',
    sampleCaption: 'Cướp 3 giây, ngã 5 giây — Karma không delay 😂 Điều 171 BLHS K1, KHÔNG phải 175! #GiậtPhoneNgãXe #Dieu171',
    hashtags: '#BinhXangCon #GiậtPhoneNgãXe #PhuongLiet113 #Dieu171BLHS #CongAnPhuongPhuongLiet #KarmaInstant #CCTV',
  },
  {
    id: 3,
    title: 'Va Chạm Nhẹ - Nổi Cáu Lớn',
    subtitle: 'Gây rối vì va chạm giao thông nhỏ',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'traffic',
    hook: 'Xước sơn 50k — la hét như mất 50 triệu? Phạt nặng hơn tiền sửa xe 🤯',
    duration: '40 giây',
    location: 'Ngã tư Phương Liệt — giờ tan tầm 17h30',
    mood: 'Va chạm nhẹ → Nổi điên over-the-top → Tắc đường → Công an → Split kết',
    viralScore: 96,
    viralLikes: '52.1K',
    viralComments: '1.8K',
    summary:
      'Đối lập viral hai thái độ sau va chạm nhẹ tại ngã tư Phương Liệt: người bình tĩnh chụp ảnh, gọi bảo hiểm, uống trà đá; BXC thì la hét, đập yên xe, chặn ngã tư, tụ tập đông người quay clip — giao thông tắc 15 phút. Công an giải quyết va chạm 30 giây, riêng BXC bị lập biên bản gây rối. Split cuối: BXC ngồi bệt / người kia thong dong. Phạt gây rối > tiền sửa xước sơn.',
    storyboard: [
      { time: '0:00', title: 'Va chạm nhẹ', desc: 'Sound "bẹp" — hai xe máy chạm nhẹ, chỉ xước sơn vài vệt. Camera zoom vết xước.', overlay: 'Va chạm nhẹ thôi mà... 🤏' },
      { time: '0:07', title: 'Nổi điên BXC', desc: 'BXC la hét, chỉ tay, đập yên xe liên tục — timelapse đám đông tụ lại quay clip.', overlay: 'Cáu lớn hơn va chạm 1000 lần! 🔥' },
      { time: '0:16', title: 'Chặn ngã tư', desc: 'BXC đứng giữa đường chặn xe. Drone shot giả: giao thông ùn tắc, còi inh ỏi.', overlay: 'Gây rối = Phạt nặng hơn tiền sửa xe' },
      { time: '0:26', title: 'Công an xử lý', desc: 'Công an đến — giải quyết va chạm 30 giây. Riêng BXC bị lập biên bản, tách khỏi đám đông.', overlay: 'Va chạm: 30 giây · Gây rối: biên bản!' },
      { time: '0:34', title: 'Outro pháp lý', desc: 'Split: BXC ngồi bệt góc đường / người kia uống trà đá vui vẻ. Text Điều 318 K1+K2.', overlay: 'Bình tĩnh = Thắng · Điều 318 BLHS', legalOutro: 'Điều 318 BLHS 2015 · Khoản 1 + Khoản 2' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Anh đâm tao! Anh đâm tao! Cả phường Phương Liệt ra mà xem! Tao không cho anh đi!' },
      { speaker: 'Người bình tĩnh', line: 'Anh ơi, xước sơn thôi, khoảng 50 nghìn. Mình chụp ảnh, gọi bảo hiểm, uống nước nhé?' },
      { speaker: 'BXC', line: 'Bảo hiểm gì! Tao đập yên xe cho anh biết tay! Ai quay clip đây — đăng lên cho nóng!' },
      { speaker: 'Công an', line: 'Va chạm hai anh giải quyết xong. Riêng anh — gây rối, chặn đường, tụ tập — lập biên bản Điều 318.' },
      { speaker: 'Voiceover', line: 'Gây rối trật tự công cộng — Điều 318 BLHS 2015 Khoản 1: phạt tiền 5–10 triệu; Khoản 2 khi chặn đường, tụ tập: tù 03 tháng – 02 năm. Va chạm nhẹ — bình tĩnh.' },
    ],
    script: [
      '【0-5s | HOOK】Sound "bẹp" nhẹ — hai xe máy dừng ngã tư Phương Liệt. Camera zoom vết xước sơn nhỏ. Text: "Va chạm nhẹ — xước sơn ~50k".',
      '【5-14s | RAGE】BXC nổi điên: la hét, chỉ tay, đập yên xe 5 lần — timelapse đám đông tụ lại, 10 người quay clip TikTok. Text đỏ: "Cáu lớn hơn va chạm".',
      '【14-22s | BLOCK】BXC đứng giữa ngã tư chặn xe. Góc drone giả từ ban công: giao thông tắc, còi inh ỏi. Text: "Gây rối trật tự công cộng".',
      '【22-32s | POLICE】Công an đến — giải quyết va chạm 30 giây (chụp ảnh, trao đổi). Riêng BXC bị tách, lập biên bản. Người bình tĩnh gật đầu.',
      '【32-40s | OUTRO | Điều 318 K1 + K2】Split screen: BXC ngồi bệt góc đường / người kia uống trà đá. Text: "Điều 318 BLHS 2015 K1: phạt 5–10 triệu · K2: tù 03 tháng – 02 năm". Logo Công an Phường Phương Liệt.',
    ],
    role: 'Người "nóng như ấm trà sôi" — diễn over-the-top kiểu drama đường phố, tương phản cực mạnh với người xử lý văn minh uống trà đá.',
    message:
      'Va chạm giao thông: bình tĩnh, chụp ảnh hiện trường, trao đổi hoặc gọi 113. Không la hét, đập phá, chặn đường, tụ tập quay clip — có thể bị phạt tiền 5–10 triệu (K1) hoặc tù 03 tháng – 02 năm (K2). Phạt gây rối thường nặng hơn tiền sửa xe.',
    cta: 'Va chạm → Bình tĩnh, ghi hình hiện trường, trao đổi bảo hiểm. Không thỏa thuận được → gọi 113. Tuyệt đối không chặn đường, đập phá.',
    legalNote:
      'La hét, đập phá, chặn đường, tụ tập đông người sau va chạm nhẹ — Điều 318 BLHS 2015: Khoản 1 (phạt tiền 5–10 triệu hoặc cải tạo đến 06 tháng); Khoản 2 (tù 03 tháng – 02 năm) khi cản trở giao thông, tụ tập đông người, đe dọa. Nghiêm hơn nhiều so với tiền sửa xước sơn.',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 318',
        name: 'Tội gây rối trật tự công cộng',
        clause: 'Khoản 1',
        text: 'Người nào gây rối trật tự công cộng ở nơi công cộng, thì bị phạt cảnh cáo, phạt tiền từ 5.000.000 đồng đến 10.000.000 đồng hoặc cải tạo không giam giữ đến 06 tháng.',
        penalty: 'Phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 06 tháng',
        applies: 'La hét, gây náo loạn, đập yên xe sau va chạm nhẹ',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 318',
        name: 'Tội gây rối trật tự công cộng',
        clause: 'Khoản 2',
        text: 'Gây rối trong trường hợp tụ tập đông người, chặn đường, cản trở giao thông, đe dọa người khác — phạt cải tạo không giam giữ đến 02 năm hoặc phạt tù từ 03 tháng đến 02 năm.',
        penalty: 'Cải tạo không giam giữ đến 02 năm hoặc tù 03 tháng – 02 năm',
        applies: 'Chặn ngã tư Phương Liệt, tụ tập quay clip, cản trở giao thông sau va chạm',
      },
    ],
    production:
      'Timelapse đám đông + drone shot giả (filter từ ban công). Split screen cuối. Outro bắt buộc: "Điều 318 BLHS 2015 — Tội gây rối trật tự công cộng · K1 + K2". Sound "bẹp" + tiếng đập yên xe.',
    sampleCaption: 'Xước sơn 50k, la hét như mất 50 triệu — Điều 318 K1+K2 đợi anh! 🤦 #VaChamBinhTinh #Dieu318',
    hashtags: '#BinhXangCon #VaChamBinhTinh #Dieu318BLHS #GayRoiCongCong #CongAnPhuongPhuongLiet #BinhTinhThang',
  },
  {
    id: 4,
    title: "Hàng Rong 'Chiếm' Vỉa Hè",
    subtitle: 'Lấn chiếm lòng lề đường',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'sidewalk',
    hook: 'Vỉa hè 1 mét — hàng chiếm 3 mét. Người già phải xuống lòng đường 🛒😤',
    duration: '32 giây',
    location: 'Phố nhỏ Phương Liệt — buổi sáng 6h30',
    mood: 'Before đau lòng → Hài nhẹ cãi vã → Công an giải thích → After ấm lòng',
    viralScore: 95,
    viralLikes: '34.6K',
    viralComments: '967',
    summary:
      'Before/After transformation viral: vỉa hè Phương Liệt biến thành "chợ mini" — hàng tràn 3 mét, người già, mẹ bỉm, xe lăn phải xuống lòng đường nguy hiểm. BXC hàng rong loa kẹo kéo, ban đầu cãi "đứng đây cho tiện" — Công an đến giải thích nhẹ nhàng theo NĐ 168/2024. Swipe transition: After — hàng gọn, vỉa hè thông, ai cũng vui. Kinh doanh được — đúng chỗ.',
    storyboard: [
      { time: '0:00', title: 'Before đau lòng', desc: 'Split-screen: vỉa hè kín hàng, chỉ còn 0 mét lối đi. Loa kẹo kéo BXC full volume.', overlay: 'BEFORE: Vỉa hè = 0 mét 😤' },
      { time: '0:08', title: 'Hậu quả thực tế', desc: 'Người già, mẹ bỉm ôm con, xe lăn không lọt — phải xuống lòng đường.', overlay: 'Vỉa hè là của CHUNG — không phải riêng ai!' },
      { time: '0:14', title: 'Công an nhắc nhẹ', desc: 'Công an đến, giải thích quy định — không la mắng. BXC ban đầu cãi, mặt "bất bình".', overlay: 'Kinh doanh OK — Nhưng ĐÚNG chỗ! ✅' },
      { time: '0:21', title: 'After transformation', desc: 'Swipe transition: BXC dọn hàng gọn, vỉa hè rộng 1.5m. Người dân đi bộ thoải mái.', overlay: 'AFTER: Ai cũng vui — Kể cả người bán!' },
      { time: '0:28', title: 'Outro pháp lý', desc: 'Text NĐ 168 Điều 20 K1 + Luật TTATGTĐB Điều 13 K1. Logo Công an Phường Phương Liệt.', overlay: 'Văn minh = Phát triển bền · NĐ 168/2024', legalOutro: 'NĐ 168/2024 Điều 20 · Khoản 1 + Luật TTATGTĐB Điều 13 K1' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Mua đi chị ơi! Rẻ lắm! 10k 3 quả! Đứng đây cho tiện — ai cũng bán thế mà!' },
      { speaker: 'Người dân', line: 'Anh ơi, nhường lối đi với. Con em đi học kìa — vỉa hè chật quá, phải xuống đường nguy hiểm!' },
      { speaker: 'Công an', line: 'Anh kinh doanh được, nhưng đúng quy định. Vỉa hè để người đi bộ — NĐ 168/2024 Điều 20, Luật TTATGTĐB Điều 13.' },
      { speaker: 'BXC', line: 'Dạ em hiểu rồi ạ. Em dọn ngay — bán vừa vừa, ai cũng qua lại được!' },
      { speaker: 'Voiceover', line: 'Lấn chiếm vỉa hè bày bán trái quy định — NĐ 168/2024/NĐ-CP Điều 20 Khoản 1: xử phạt hành chính, buộc khắc phục. Luật TTATGTĐB Điều 13 K1: nghiêm cấm chiếm vỉa hè kinh doanh.' },
    ],
    script: [
      '【0-5s | BEFORE】Split-screen: vỉa hè kín hàng BXC, người chen chúc. Loa kẹo kéo. Text đỏ: "Vỉa hè 1m — hàng chiếm 3m".',
      '【5-12s | IMPACT】Người già, mẹ bỉm ôm con, xe lăn không lọt — phải xuống lòng đường. Text cảnh báo: "Nguy hiểm — vỉa hè là của chung".',
      '【12-19s | DIALOGUE】Công an đến, giải thích nhẹ nhàng NĐ 168 + Luật TTATGTĐB. BXC ban đầu cãi "ai cũng bán thế", mặt bất bình (hài nhẹ).',
      '【19-26s | AFTER】Transition swipe mượt: hàng gọn trong vạch, vỉa hè rộng. Người dân thumbs up, BXC vẫn bán được.',
      '【26-32s | OUTRO | NĐ 168 Điều 20 K1 + Luật TTATGTĐB Điều 13 K1】Text: "NĐ 168/2024 Điều 20 K1 — Xử phạt lấn chiếm vỉa hè · Luật TTATGTĐB Điều 13 K1 — Nghiêm cấm". Logo Công an Phường Phương Liệt.',
    ],
    role: 'Hàng rong "ban đầu cứng, sau mềm" — tôn trọng người lao động chân chính, không chế giễu nghề, arc tích cực khi hiểu quy định.',
    message: 'Không lấn chiếm vỉa hè, lòng đường để bày bán. Kinh doanh có trật tự = an toàn cho người đi bộ + văn minh + bán bền vững. Vỉa hè là của cộng đồng — không phải riêng ai.',
    cta: 'Phản ánh lấn chiếm hè phố → Hotline Công an Phường Phương Liệt. Ghi hình, gửi địa chỉ cụ thể.',
    legalNote:
      'Lấn chiếm vỉa hè, bày bán tràn ra lòng đường bị xử phạt hành chính theo Nghị định 168/2024/NĐ-CP Điều 20 Khoản 1; căn cứ Luật Trật tự, an toàn giao thông đường bộ Điều 13 Khoản 1 — nghiêm cấm lấn chiếm vỉa hè kinh doanh trái quy định. Buộc dọn, khắc phục, tịch thu tang vật.',
    legalArticles: [
      {
        code: 'NĐ 168/2024',
        law: LAW_REF.ND168,
        article: 'Điều 20',
        name: 'Xử phạt lấn chiếm lòng đường, vỉa hè',
        clause: 'Khoản 1',
        text: 'Lấn chiếm một phần lòng đường, vỉa hè; bày bán hàng hóa, thiết lập điểm kinh doanh dịch vụ trên lòng đường, vỉa hè trái quy định — bị xử phạt vi phạm hành chính, tịch thu tang vật, buộc khắc phục hậu quả.',
        penalty: 'Phạt tiền (cá nhân/tổ chức) và buộc dọn, khắc phục hậu quả',
        applies: 'Hàng rong, quán ăn, bày bán chiếm vỉa hè Phương Liệt',
      },
      {
        code: 'Luật TTATGTĐB',
        law: LAW_REF.LTATGT,
        article: 'Điều 13',
        name: 'Bảo đảm lòng đường, vỉa hè thông thoáng',
        clause: 'Khoản 1',
        text: 'Nghiêm cấm lấn chiếm lòng đường, vỉa hè để tổ chức, kinh doanh, bày bán hàng hóa, thiết lập điểm kinh doanh dịch vụ trái quy định của pháp luật.',
        penalty: 'Xử phạt hành chính theo NĐ 168/2024/NĐ-CP',
        applies: 'Mọi hình thức chiếm dụng vỉa hè làm điểm bán hàng, kinh doanh',
      },
    ],
    production:
      'Before/After swipe transition mượt. Split-screen người già/xe lăn. Outro bắt buộc: "NĐ 168/2024 Điều 20 K1 + Luật TTATGTĐB Điều 13 K1". Loa kẹo kéo prop. Tone tôn trọng người lao động.',
    sampleCaption: 'Vỉa hè 1m chiếm 3m — người già phải xuống đường 😤 NĐ 168 Điều 20 K1 nhắc nhẹ! #ViaHeKhongPhaiRiengAi',
    hashtags: '#BinhXangCon #ViaHeKhongPhaiRiengAi #ND1682024 #LuatTTATGTDB #CongAnPhuongPhuongLiet #KinhDoanhCoTratTu',
  },
  {
    id: 5,
    title: 'Cá Độ Thua Sạch - Trộm Để Gỡ',
    subtitle: 'Hệ lụy cờ bạc, cá độ',
    category: 'ca-do',
    categoryLabel: 'Cá độ & Cờ bạc',
    scene: 'drama',
    hook: 'Thua cá độ 47 triệu → Bạn rủ trộm xe gỡ → Công an đúng lúc 💸🚨',
    duration: '38 giây',
    location: 'Quán nước vỉa hè Phương Liệt — đêm Champions League',
    mood: 'Drama đen → Domino tội phạm → Hài đen tỉ táo → Bị bắt → Dual outro',
    viralScore: 97,
    viralLikes: '67.4K',
    viralComments: '2.1K',
    summary:
      'Domino tội phạm trong 38 giây gây sốc: BXC thua cá độ bóng đá -47 triệu, mặt tái mét — bạn thì thầm "trộm xe Wave kia, 5 phút gỡ xong". BXC gật đầu mặt "tỉ táo" như đang tính ROI, tay run rút chìa — đúng lúc đèn flash Công an tuần tra. Freeze frame zoom mặt. Một clip, hai tội danh: Điều 321 + Điều 173. Cá độ = con đường chết.',
    storyboard: [
      { time: '0:00', title: 'Thua sạch', desc: 'Close-up mặt BXC, phone hiện "THUA -47.000.000đ" đỏ chót. Nhạc dramatic.', overlay: 'Thua sạch... 47 triệu 💀' },
      { time: '0:08', title: 'Rủ trộm gỡ', desc: 'Bạn thì thầm chỉ xe Wave đậu gần. BXC nhìn xe như nhìn ATM.', overlay: 'Cá độ → Nợ → Phạm pháp — Domino!' },
      { time: '0:16', title: 'Hành động tỉ táo', desc: 'BXC tiến tới xe, tay run rút chìa — mặt suy tính hài hước. Camera handheld rung.', overlay: 'Đừng đi con đường này! ⛔' },
      { time: '0:24', title: 'Plot twist bắt quả tang', desc: 'Đèn flash Công an tuần tra. BXC quay lại — freeze frame 2s + zoom mặt meme.', overlay: 'Plot twist: Công an đến đúng lúc 👮' },
      { time: '0:32', title: 'Outro dual pháp lý', desc: 'Text Điều 321 K1 + Điều 173 K1 song song. Hotline tư vấn + logo Phường Phương Liệt.', overlay: 'Cá độ + Trộm cắp = Hai tội danh · BLHS', legalOutro: 'Điều 321 BLHS 2015 · Khoản 1 + Điều 173 BLHS 2015 · Khoản 1' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Thua hết rồi... 47 triệu... Trận này em all-in... Sao giờ này đây...' },
      { speaker: 'Bạn', line: 'Trộm cái xe Wave kia đi. Gỡ xong trả nợ. 5 phút thôi — không ai biết!' },
      { speaker: 'BXC', line: 'Ừ... ROI cao đấy... Nhưng mà... ủa, sao có đèn flash công an ở đây?!' },
      { speaker: 'Công an', line: 'Anh vừa nói gì? Và cái chìa khoa trong tay anh — xe của ai?' },
      { speaker: 'Voiceover', line: 'Đánh bạc trái phép thua từ 5 triệu — Điều 321 BLHS 2015 Khoản 1: phạt tiền 20–100 triệu hoặc tù 06 tháng – 03 năm. Trộm xe gỡ nợ — thêm Điều 173 Khoản 1: tù 06 tháng – 03 năm. Xử lý nhiều tội danh.' },
    ],
    script: [
      '【0-5s | HOOK】Close-up mặt BXC tái mét, phone hiện "THUA -47.000.000đ" đỏ. Nhạc dramatic + tiếng notification liên tục. Text: "Domino tội phạm bắt đầu".',
      '【5-13s | TEMPT】Bạn thì thầm chỉ xe Wave — BXC do dự, mặt "suy tính ROI" hài hước (meme tỉ táo). Text: "Cá độ → Nợ → Phạm pháp".',
      '【13-21s | ACTION】BXC tiến tới xe máy, tay run rút chìa — camera handheld rung theo nhịp tim. Nhạc căng thẳng.',
      '【21-29s | TWIST】Đèn flash Công an tuần tra qua. BXC quay lại — freeze frame 2 giây + zoom mặt "trăm ngàn lỗi lầm".',
      '【29-38s | OUTRO | Điều 321 K1 + Điều 173 K1】Dual text song song: "Điều 321 BLHS 2015 K1 — Đánh bạc trái phép: tù 06 tháng – 03 năm" | "Điều 173 BLHS 2015 K1 — Trộm cắp: tù 06 tháng – 03 năm". Hotline tư vấn. Logo Công an Phường Phương Liệt.',
    ],
    role: 'Người sa vào nợ nần — biểu cảm "tỉ táo tính ROI" khi quyết định phạm pháp hài đen, kết cục freeze frame đáng nhớ.',
    message: 'Cá độ, cờ bạc trái phép = vi phạm pháp luật (Điều 321). Dễ dẫn đến nợ nần, gian lận, trộm cắp (Điều 173) — domino tội phạm. Không tham gia, không tổ chức, không "gỡ" bằng phạm pháp.',
    cta: 'Phát hiện tụ cá độ, cờ bạc → Tố giác Công an Phường Phương Liệt ngay. Có thể tố giác ẩn danh. Hotline tư vấn nợ nần, cờ bạc.',
    legalNote:
      'Cá độ trái phép thua từ 5.000.000 đồng trở lên hoặc tái phạm: Điều 321 BLHS 2015 Khoản 1 (phạt tiền 20–100 triệu, cải tạo đến 03 năm hoặc tù 06 tháng – 03 năm). Trộm xe máy gỡ nợ: thêm Điều 173 Khoản 1 (tù 06 tháng – 03 năm) — có thể bị xử lý nhiều tội danh cùng lúc theo quy định hình sự.',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 321',
        name: 'Tội đánh bạc',
        clause: 'Khoản 1',
        text: 'Người nào đánh bạc trái phép (cá độ, lô đề, cờ bạc trực tuyến), thua từ 5.000.000 đồng trở lên hoặc tái phạm, thì bị phạt tiền từ 20.000.000 đến 100.000.000 đồng, cải tạo không giam giữ đến 03 năm hoặc phạt tù từ 06 tháng đến 03 năm.',
        penalty: 'Phạt tiền 20–100 triệu, cải tạo đến 03 năm hoặc tù 06 tháng – 03 năm',
        applies: 'Cá độ bóng đá, game, lô đề online, cờ bạc trực tuyến',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 173',
        name: 'Tội trộm cắp tài sản',
        clause: 'Khoản 1',
        text: 'Người nào trộm cắp tài sản của người khác có giá trị từ 2.000.000 đồng đến dưới 50.000.000 đồng — trộm xe máy để gỡ nợ cá độ: phạt tù từ 06 tháng đến 03 năm hoặc cải tạo không giam giữ đến 03 năm.',
        penalty: 'Tù 06 tháng – 03 năm hoặc cải tạo không giam giữ đến 03 năm',
        applies: 'Trộm xe máy, ô tô, tài sản vì nợ cờ bạc, cá độ',
      },
    ],
    production:
      'Phone prop hiện -47.000.000đ đỏ. Freeze frame 2s khi bắt. Dual outro text song song Điều 321 + 173. Handheld rung khi rút chìa. Outro: "Điều 321 K1 + Điều 173 K1 BLHS 2015".',
    sampleCaption: 'Thua 47 triệu rồi trộm xe gỡ? Điều 321 + 173 BLHS chờ sẵn — domino tội phạm! 💸 #CaDoLaConDuongChet',
    hashtags: '#BinhXangCon #CaDoLaConDuongChet #Dieu321BLHS #Dieu173BLHS #CongAnPhuongPhuongLiet #DominoToiPham',
  },
  {
    id: 6,
    title: 'Kẻ Lạ Theo Dõi - Báo Ngay Công An',
    subtitle: 'Cảnh giác an toàn cá nhân — theo dõi quấy rối',
    category: 'to-giac',
    categoryLabel: 'Tố giác & Cảnh giác',
    scene: 'night',
    hook: 'Theo sau 200m — Đừng im lặng! 🌙',
    duration: '42 giây',
    location: 'Ngõ nhỏ Phương Liệt — buổi tối',
    mood: 'Thriller POV → Twist hài → Outro pháp lý cứng',
    viralScore: 93,
    viralLikes: '18.9K',
    viralComments: '512',
    summary:
      'Premium thriller-comedy 42 giây: POV phụ nữ đi về nhà, BXC bám theo 200m — nhịp tim tăng từng mét. Cô không chạy một mình mà lao vào tiệm đông người, gọi 113 theo đúng quyền tố giác. Twist: BXC đi nhầm ngõ. Outro Voiceover đọc nguyên văn BLTTHS Điều 143 K1 + BLHS Điều 132 K1 — dù nhầm hay thật, an toàn luôn thắng.',
    storyboard: [
      { time: '0:00', title: 'Hook POV', desc: 'Selfie POV đi bộ đêm, bước chân vang vọng ngõ vắng — text to 3 giây.', overlay: '9PM — Một mình về nhà 🌙' },
      { time: '0:08', title: 'Bám theo', desc: 'Góc sau: BXC cách 5m, nhạc heartbeat. Phụ nữ quay lại — tăng tốc.', overlay: 'Theo sau 200m — Đừng im lặng!' },
      { time: '0:18', title: 'Hành động đúng', desc: 'Lao vào tiệm tạp hóa đông người, chủ quán khóa cửa, bấm 113.', overlay: 'Vào nơi đông người → Báo ngay!' },
      { time: '0:28', title: 'Twist nhầm ngõ', desc: 'BXC giơ map phone, mặt "trăm ngàn lỗi lầm": "Em tìm nhà bạn ạ!"', overlay: 'Plot twist: Nhầm đường 😅' },
      { time: '0:36', title: 'Outro pháp lý', desc: 'Text điều luật full màn + logo Công an. VO đọc hình phạt theo dõi.', overlay: 'An toàn > Ngại ngần', legalOutro: 'BLTTHS Điều 143 K1 + BLHS Điều 132 K1 — Tố giác & Theo dõi quấy rối' },
    ],
    dialogues: [
      { speaker: 'Phụ nữ (thì thầm)', line: 'Sao người này theo mình hoài... 200 mét rồi...' },
      { speaker: 'Chủ quán', line: 'Chị vào đây! Em khóa cửa, gọi 113 ngay — đừng sợ!' },
      { speaker: 'BXC', line: 'Dạ em xin lỗi chị! Em đi nhầm ngõ, em tìm nhà bạn ở số 14...' },
      { speaker: 'Công an (phone)', line: 'Chị mô tả đặc điểm người theo sau. Đội tuần tra đang đến.' },
      { speaker: 'Voiceover', line: 'Theo BLTTHS 2015 Điều 143 Khoản 1: Mọi công dân có quyền tố giác, báo tin về tội phạm đến cơ quan Công an — tiếp nhận, xử lý kịp thời.' },
      { speaker: 'Voiceover', line: 'Theo dõi, quấy rối gây lo sợ — BLHS 2015 Điều 132 Khoản 1: phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 02 năm.' },
    ],
    script: [
      '【0-3s | HOOK】Selfie POV ngõ tối Phương Liệt. Text trending: "Khi bạn cảm thấy bị theo dõi". Sound heartbeat.',
      '【3-12s】Góc sau handheld: BXC bám 5m. Phụ nữ quay lại — zoom mắt hoảng. Counter overlay: "200m".',
      '【12-22s】Cô lao vào tiệm tạp hóa sáng đèn. Chủ quán khóa cửa, gọi 113 — split screen phone + camera ngoài.',
      '【22-32s | TWIST】BXC xin lỗi, chỉ map "đi nhầm ngõ 14". Cả tiệm exhale — relief comedy beat 2 giây.',
      '【32-42s | OUTRO | BLTTHS Điều 143 K1 + BLHS Điều 132 K1】Text overlay điều luật. Voiceover đọc nguyên văn quyền tố giác + hình phạt theo dõi. Logo Công an Phường Phương Liệt. CTA: "Cảm thấy nguy hiểm — gọi 113, không ngại."',
    ],
    role: 'Kẻ "đáng ngờ" — suspense tối đa, twist hài không làm suy giảm thông điệp: luôn báo khi không an toàn.',
    message: 'Đi đường muộn: chọn đường sáng, tránh ngõ vắng. Tin cảm giác nguy hiểm — vào nơi đông người, gọi 113 ngay. Dù sau đó là nhầm đường, hành động vẫn đúng.',
    cta: 'Nguy hiểm cấp bách → Gọi 113. Mô tả người, trang phục, hướng di chuyển, địa điểm chính xác.',
    legalNote:
      'Cảm thấy bị theo dõi, quấy rối — báo ngay theo BLTTHS Điều 143 Khoản 1 (quyền tố giác). Hành vi theo dõi gây lo sợ, ảnh hưởng an toàn: BLHS 2015 Điều 132 Khoản 1 — phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 02 năm.',
    legalArticles: [
      {
        code: 'BLTTHS 2015',
        law: LAW_REF.BLTTHS,
        article: 'Điều 143',
        name: 'Tố giác, tin báo về tội phạm',
        clause: 'Khoản 1',
        text: 'Mọi công dân có quyền tố giác, báo tin về tội phạm đến cơ quan Công an, Viện kiểm sát hoặc Tòa án. Cơ quan có trách nhiệm tiếp nhận, xử lý kịp thời theo quy định của Bộ luật này.',
        penalty: 'Không xử phạt người báo tin trung thực; được bảo vệ theo Điều 144 BLTTHS',
        applies: 'Gọi 113 khi cảm thấy bị theo dõi, nguy hiểm — kể cả khi sau đó xác định nhầm đường',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 132',
        name: 'Hành vi trái với đạo đức xã hội',
        clause: 'Khoản 1',
        text: 'Người nào có hành vi trái với đạo đức xã hội, gây ảnh hưởng xấu đến an ninh, trật tự, an toàn xã hội, thì bị phạt cảnh cáo, phạt tiền từ 5.000.000 đồng đến 10.000.000 đồng hoặc phạt cải tạo không giam giữ đến 02 năm.',
        penalty: 'Phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 02 năm',
        applies: 'Theo dõi, quấy rối, gây lo sợ cho người đi đường về nhà một mình',
      },
    ],
    production: 'Quay dọc 9:16, POV + góc sau. Outro bắt buộc: "BLTTHS Điều 143 K1 + BLHS Điều 132 K1". Nhạc suspense → relief → VO pháp lý.',
    sampleCaption: 'Theo 200m mà im? BLTTHS Điều 143 K1 bảo vệ bạn! 🌙 #BaoNgay113 #Dieu132BLHS',
    hashtags: '#BinhXangCon #BaoNgay113 #Dieu143BLTTHS #Dieu132BLHS #PhuongLietAnToan #CongAnPhuongPhuongLiet',
  },
  {
    id: 7,
    title: "Va Chạm 'Tình Cờ' - Móc Túi Tinh Vi",
    subtitle: 'Trộm cắp tinh vi tại chợ đông người',
    category: 'trom-cap',
    categoryLabel: 'Trộm cắp & Cướp giật',
    scene: 'market',
    hook: 'Xin lỗi 180 lần — Móc túi 1 lần 🎭',
    duration: '34 giây',
    location: 'Chợ Phương Liệt — sáng cuối tuần',
    mood: 'Split-screen viral → Bắt quả tang → Outro Điều 173 K1+K2',
    viralScore: 97,
    viralLikes: '24.8K',
    viralComments: '734',
    summary:
      'Viral masterclass móc túi chợ: BXC va chạm "tình cờ" liên tục, mặt cười diplomatic, tay móc túi không ngừng — split-screen "hai mặt" là meme format. Bị bắt quả tang nhờ người bán + CCTV. Outro Voiceover đọc BLHS Điều 173 Khoản 1 (móc túi thường) và Khoản 2 (trộm chuyên nghiệp/tổ chức).',
    storyboard: [
      { time: '0:00', title: 'Hook chợ đông', desc: 'Wide shot chợ Phương Liệt cuối tuần — zoom BXC len lỏi giữa đám đông.', overlay: 'Chợ đông = Mục tiêu vàng? 🛒' },
      { time: '0:06', title: 'Va chạm giả', desc: 'BXC "vô tình" va vai, xin lỗi 3 lần trong 2 giây.', overlay: 'Va chạm tình cờ... hay có chủ đích?' },
      { time: '0:14', title: 'Split-screen', desc: 'Trái: mặt cười xin lỗi. Phải: tay luồn túi xách — text "HAI MẶT".', overlay: 'Xin lỗi 180 lần — Móc túi 1 lần 🎭' },
      { time: '0:22', title: 'Bắt quả tang', desc: 'Người bán hét, đám đông vây. Ví rơi — CCTV zoom freeze.', overlay: 'Móc túi có chủ — Camera không nói dối!' },
      { time: '0:30', title: 'Outro pháp lý', desc: 'Text Điều 173 K1+K2 + hướng dẫn túi trước ngực.', overlay: 'Để túi trước ngực — Khóa kỹ!', legalOutro: 'BLHS Điều 173 Khoản 1 + Khoản 2 — Tội trộm cắp tài sản' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Dạ em xin lỗi chị! Em xin lỗi! Em lỡ tay! Chị tha cho em lần nữa!' },
      { speaker: 'Nạn nhân', line: 'Anh va em 5 lần rồi. Tay anh đang trong túi em kìa?!' },
      { speaker: 'Người bán', line: 'Có trộm! Bắt tay nó lại! Camera góc kia quay hết!' },
      { speaker: 'BXC', line: 'Không phải! Em... em tìm hộp quẹt thôi! Em hay quên để ở túi người lạ!' },
      { speaker: 'Voiceover', line: 'BLHS 2015 Điều 173 Khoản 1: Trộm cắp tài sản từ 2 triệu đến dưới 50 triệu — phạt tù 06 tháng đến 03 năm hoặc cải tạo không giam giữ.' },
      { speaker: 'Voiceover', line: 'Điều 173 Khoản 2: Trộm cắp có tổ chức, tính chất chuyên nghiệp hoặc tài sản 50–200 triệu — phạt tù từ 02 đến 07 năm.' },
    ],
    script: [
      '【0-3s | HOOK】Wide shot chợ đông Phương Liệt. Text trending: "Khi kẻ trộm xin lỗi nhiều hơn bạn mua hàng".',
      '【3-10s】BXC va chạm "vô tình" — xin lỗi liên tục, không ngừng, mặt vô tội cực đại.',
      '【10-18s | SPLIT】Trái: mặt cười diplomatic. Phải: tay móc túi slow-mo. Counter: "Xin lỗi #47".',
      '【18-26s】Người bán hét "Có trộm!". Đám đông vây. BXC giơ tay — ví rơi slow-mo. CCTV overlay freeze.',
      '【26-34s | OUTRO | BLHS Điều 173 K1 + K2】Text overlay điều luật + hình phạt. Voiceover đọc K1 và K2. Logo Công an Phường Phương Liệt. CTA: "Túi trước ngực, khóa kỹ — báo 113 khi mất trộm."',
    ],
    role: 'Kẻ móc túi "diplomat" — split-screen hai mặt là peak viral, hài nhưng đáng sợ, không glamorize tội phạm.',
    message: 'Chợ, siêu thị, lễ hội đông người: túi để trước ngực, khóa kỹ, không để túi sau. Va chạm cố ý → kiểm tra ví, điện thoại ngay.',
    cta: 'Mất trộm tại chợ → Báo ban quản lý + 113. Cung cấp thời gian, vị trí, clip camera an ninh.',
    legalNote:
      'Móc túi tại chợ đông người — BLHS 2015 Điều 173 Khoản 1 (tài sản 2–50 triệu: tù 06 tháng – 03 năm). Trộm có tổ chức, chuyên nghiệp hoặc 50–200 triệu: Khoản 2 (tù 02–07 năm).',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 173',
        name: 'Tội trộm cắp tài sản',
        clause: 'Khoản 1',
        text: 'Người nào trộm cắp tài sản của người khác có giá trị từ 2.000.000 đồng đến dưới 50.000.000 đồng (hoặc dưới 2.000.000 đồng kèm tình tiết tăng nặng), thì bị phạt cải tạo không giam giữ đến 03 năm hoặc phạt tù từ 06 tháng đến 03 năm.',
        penalty: 'Cải tạo không giam giữ đến 03 năm hoặc tù 06 tháng – 03 năm',
        applies: 'Móc túi, trộm ví, điện thoại tại chợ Phương Liệt',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 173',
        name: 'Tội trộm cắp tài sản',
        clause: 'Khoản 2',
        text: 'Trộm cắp tài sản có giá trị từ 50.000.000 đồng đến dưới 200.000.000 đồng; hoặc trộm cắp có tổ chức; hoặc trộm cắp có tính chất chuyên nghiệp — phạt tù từ 02 năm đến 07 năm.',
        penalty: 'Phạt tù từ 02 năm đến 07 năm',
        applies: 'Kẻ trộm chuyên nghiệp, móc túi có tổ chức tại nơi đông người',
      },
    ],
    production: 'Split-screen mặt/tay bắt buộc. Outro: "BLHS Điều 173 K1 + K2". Sound "ding" khi bắt quả tang + CCTV freeze.',
    sampleCaption: 'Xin lỗi 180 lần, móc túi 1 lần — Điều 173 K1+K2 không tha! 🎭 #MocTuiTinhVi',
    hashtags: '#BinhXangCon #MocTuiTinhVi #Dieu173BLHS #ChoPhuongLiet #CongAnPhuongPhuongLiet #DungDeViBay',
  },
  {
    id: 8,
    title: 'Đánh Bài Quán Cà Phê - Bị Bắt Quả Tang',
    subtitle: 'Tụ điểm cờ bạc công cộng',
    category: 'ca-do',
    categoryLabel: 'Cá độ & Cờ bạc',
    scene: 'cards',
    hook: 'Ảo thuật gia hết thuốc — Bị bắt quả tang 🃏',
    duration: '36 giây',
    location: 'Quán cà phê vỉa hè Phương Liệt',
    mood: 'Magic fail comedy → Bắt quả tang → Outro Điều 321+322',
    viralScore: 92,
    viralLikes: '16.7K',
    viralComments: '489',
    summary:
      'BXC "ảo thuật gia" rút bài từ tay áo giữa ván bài ăn tiền tại quán vỉa hè — slow-mo magic fail, cãi "bài tự bay", công an ập vào thu bài tiền. Outro Voiceover đọc BLHS Điều 321 K1 (đánh bạc) + Điều 322 K1 (tổ chức/gá bạc). Một clip, hai tội danh.',
    storyboard: [
      { time: '0:00', title: 'Hook ván bài', desc: 'Top-down 4 người, tiền prop trên bàn — text 3 giây.', overlay: 'Chơi bài ăn tiền = Vi phạm! 🃏' },
      { time: '0:08', title: 'Ảo thuật fail', desc: 'BXC rút bài từ tay áo — slow-mo, nhạc magic, bị lộ ngay.', overlay: 'Ảo thuật gia BXC — Hết thuốc 🎩' },
      { time: '0:16', title: 'Cãi vã hài', desc: '"Bài tự bay vào tay áo!" — đối thủ chỉ camera quán.', overlay: 'Camera quán quay hết — Đừng cãi!' },
      { time: '0:24', title: 'Công an vào', desc: 'Kiểm tra, thu bài tiền prop. BXC viết cam kết — meme face.', overlay: 'Công an lập biên bản 👮' },
      { time: '0:32', title: 'Outro pháp lý', desc: 'Text Điều 321+322 + hotline tố giác cờ bạc.', overlay: 'Cờ bạc = Hình sự', legalOutro: 'BLHS Điều 321 K1 + Điều 322 K1 — Đánh bạc & Tổ chức cờ bạc' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Tôi bị oan! Bài tự nhiên... bay vào tay áo tôi! Tôi là ảo thuật gia!' },
      { speaker: 'Bạn chơi', line: 'Bay vào tay áo? Anh tưởng camera quán mù à?! Tiền trên bàn đây!' },
      { speaker: 'Chủ quán', line: 'Tôi gọi công an rồi. Anh em chơi bài ăn tiền trước quán tôi — không được!' },
      { speaker: 'Công an', line: 'Đánh bài ăn tiền tại nơi công cộng — lập biên bản. Ai tổ chức bàn này?' },
      { speaker: 'Voiceover', line: 'BLHS 2015 Điều 321 Khoản 1: Đánh bạc trái phép, thua từ 5.000.000 đồng trở lên — phạt tiền 20–100 triệu, cải tạo không giam giữ đến 03 năm hoặc tù 06 tháng – 03 năm.' },
      { speaker: 'Voiceover', line: 'Điều 322 Khoản 1: Tổ chức đánh bạc, gá bạc hoặc làm cái — phạt tiền 50–300 triệu hoặc phạt tù từ 01 đến 05 năm.' },
    ],
    script: [
      '【0-3s | HOOK】Top-down bàn bài + tiền prop. Text: "Tụ điểm cờ bạc mini — quán vỉa hè Phương Liệt".',
      '【3-12s】BXC rút bài từ tay áo — slow-mo 0.5x, nhạc magic. Đối thủ phát hiện — zoom mắt.',
      '【12-20s】Cãi vã hài "bài tự bay". Chủ quán chỉ camera góc trần — split screen CCTV.',
      '【20-28s】Công an vào kiểm tra. Thu bài, tiền prop. BXC ngồi góc viết cam kết — freeze meme face.',
      '【28-36s | OUTRO | BLHS Điều 321 K1 + Điều 322 K1】Text overlay điều luật. Voiceover đọc hình phạt đánh bạc + tổ chức. Logo Công an Phường Phương Liệt. CTA: "Phát hiện cờ bạc — tố giác ngay."',
    ],
    role: 'Ảo thuật gia thất bại — comedy peak "bài bay vào tay áo", kết nghiêm khi công an vào.',
    message: 'Đánh bài ăn tiền tại quán công cộng = cờ bạc trái phép. Người chơi và người tổ chức đều bị xử lý hình sự.',
    cta: 'Phát hiện tụ cờ bạc → Tố giác ẩn danh hoặc gọi hotline Công an Phường Phương Liệt.',
    legalNote:
      'Đánh bài ăn tiền tại quán công cộng — BLHS 2015 Điều 321 Khoản 1 (đánh bạc trái phép). Tổ chức, gá bạc, làm cái: Điều 322 Khoản 1 (tù 01–05 năm hoặc phạt tiền 50–300 triệu).',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 321',
        name: 'Tội đánh bạc',
        clause: 'Khoản 1',
        text: 'Người nào đánh bạc trái phép, thua cược từ 5.000.000 đồng trở lên hoặc đã bị xử phạt vi phạm hành chính về hành vi này mà tái phạm, thì bị phạt tiền từ 20.000.000 đồng đến 100.000.000 đồng, phạt cải tạo không giam giữ đến 03 năm hoặc phạt tù từ 06 tháng đến 03 năm.',
        penalty: 'Phạt tiền 20–100 triệu, cải tạo đến 03 năm hoặc tù 06 tháng – 03 năm',
        applies: 'Chơi bài ăn tiền tại quán cà phê vỉa hè Phương Liệt',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 322',
        name: 'Tội tổ chức đánh bạc hoặc gá bạc',
        clause: 'Khoản 1',
        text: 'Người nào tổ chức đánh bạc, gá bạc hoặc làm cái, thì bị phạt tiền từ 50.000.000 đồng đến 300.000.000 đồng hoặc phạt tù từ 01 năm đến 05 năm.',
        penalty: 'Phạt tiền 50–300 triệu hoặc tù 01 – 05 năm',
        applies: 'Chủ bàn bài, người tổ chức tụ điểm cờ bạc mini tại quán công cộng',
      },
    ],
    production: 'Top-down bàn bài + CCTV split. Outro: "BLHS Điều 321 K1 + Điều 322 K1". Tiền prop, không tiền thật.',
    sampleCaption: 'Bài bay vào tay áo? Điều 321+322 bắt quả tang! 🃏 #CoBacKhongVui #Dieu321 #Dieu322',
    hashtags: '#BinhXangCon #CoBacKhongVui #Dieu321BLHS #Dieu322BLHS #CongAnPhuongPhuongLiet',
  },
  {
    id: 9,
    title: "Say Xỉn Gây Rối - 'Ngáo' Giữa Đường Phố",
    subtitle: 'Gây rối trật tự khi say rượu',
    category: 'gay-roi',
    categoryLabel: 'Gây rối trật tự công cộng',
    scene: 'night',
    hook: 'Say ≠ Được phép ngáo giữa đường 🍺',
    duration: '38 giây',
    location: 'Lòng đường Phương Liệt — đêm cuối tuần',
    mood: 'Party fail viral → Physical comedy → Outro Điều 318+260',
    viralScore: 95,
    viralLikes: '29.3K',
    viralComments: '967',
    summary:
      'BXC say xỉn đứng giữa lòng đường hát karaoke không mic, chắn xe, nhảy múa — 3 bạn kéo không nổi (physical comedy peak). Công an đến đưa về an toàn. Outro Voiceover: BLHS Điều 318 K1 (gây rối say rượu) + Điều 260 K2đ (lái xe khi say). Say không phải giấy phép ngáo.',
    storyboard: [
      { time: '0:00', title: 'Hook say xỉn', desc: 'BXC giữa lòng đường hát to, xe máy vòng quanh — text 3 giây.', overlay: 'Say xỉn + Giữa đường = 🚨' },
      { time: '0:08', title: 'Chắn xe còi', desc: 'Ô tô, xe máy bấm còi liên tục — BXC vẫn nhảy, không nhường.', overlay: 'Say ≠ Được phép gây rối!' },
      { time: '0:16', title: '3 vs 1 fail', desc: 'Ba bạn kéo BXC — vẫn hát. Comedy physical, timelapse 5 giây.', overlay: '3 người kéo — 1 người thắng 😂' },
      { time: '0:26', title: 'Công an xử lý', desc: 'Công an đến nhẹ nhàng, đưa lên xe. BXC ngủ gật — hài kết.', overlay: 'Gọi 113 — Đừng đối đầu một mình' },
      { time: '0:34', title: 'Outro pháp lý', desc: 'Text Điều 318 K1 + 260 K2đ + "Uống có trách nhiệm".', overlay: 'Uống có trách nhiệm — Không lái say', legalOutro: 'BLHS Điều 318 K1 + Điều 260 K2đ — Gây rối & Lái xe khi say' },
    ],
    dialogues: [
      { speaker: 'BXC', line: 'Tôi là... tôi là... ngôi sao đường phố Phương Liệt! Cho tôi mic! Không mic cũng hát!' },
      { speaker: 'Bạn bè', line: 'Về thôi! Xe còi kìa! Công an tới rồi! Mày muốn lên biên bản à?!' },
      { speaker: 'Tài xế', line: 'Anh nhường đường đi! Chắn giữa lòng đường — tai nạn thì sao?!' },
      { speaker: 'Công an', line: 'Anh về nhà nghỉ. Say rượu gây rối trật tự công cộng — anh nghe em nhắc nhé.' },
      { speaker: 'Voiceover', line: 'BLHS 2015 Điều 318 Khoản 1: Gây rối trật tự công cộng ở nơi công cộng — phạt cảnh cáo, phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 06 tháng.' },
      { speaker: 'Voiceover', line: 'Điều 260 Khoản 2 điểm đ: Lái xe ô tô, mô tô, xe gắn máy... trong tình trạng có nồng độ cồn vượt quy định — phạt tù từ 01 đến 05 năm, hoặc 03–10 năm nếu gây hậu quả nghiêm trọng.' },
    ],
    script: [
      '【0-3s | HOOK】Đêm cuối tuần Phương Liệt. BXC giữa lòng đường hát karaoke không mic. Text: "Say ≠ Được phép ngáo".',
      '【3-12s】Xe máy, ô tô bấm còi liên tục. BXC nhảy múa, chắn đường — góc drone giả nhìn tắc.',
      '【12-22s】3 bạn kéo — BXC vẫn hát. Timelapse physical comedy "3 vs 1". Counter còi xe.',
      '【22-30s】Công an đến, nhẹ nhàng đưa lên xe. BXC ngủ gật ngay — comedy beat.',
      '【30-38s | OUTRO | BLHS Điều 318 K1 + Điều 260 K2đ】Text overlay điều luật. Voiceover đọc hình phạt gây rối + lái xe say. Logo Công an Phường Phương Liệt. CTA: "Uống có trách nhiệm — không lái xe khi say."',
    ],
    role: 'Người say "ngáo" — physical comedy 3-vs-1, hậu quả phiền phức nhưng xử lý nhẹ nhàng, không glamorize.',
    message: 'Say rượu không được gây rối, chắn đường, đánh nhau. Uống xong không lái xe. Vi phạm → phạt HC hoặc truy cứu hình sự.',
    cta: 'Gặp người say gây rối → Gọi 113, không đối đầu một mình. Nhắc bạn bè uống có trách nhiệm.',
    legalNote:
      'Say rượu gây rối, chắn đường — BLHS 2015 Điều 318 Khoản 1 (phạt tiền 5–10 triệu hoặc cải tạo đến 06 tháng). Lái xe khi nồng độ cồn vượt quy định: Điều 260 Khoản 2 điểm đ (tù 01–05 năm; 03–10 năm nếu gây hậu quả nghiêm trọng).',
    legalArticles: [
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 318',
        name: 'Tội gây rối trật tự công cộng',
        clause: 'Khoản 1',
        text: 'Người nào gây rối trật tự công cộng ở nơi công cộng, thì bị phạt cảnh cáo, phạt tiền từ 5.000.000 đồng đến 10.000.000 đồng hoặc phạt cải tạo không giam giữ đến 06 tháng.',
        penalty: 'Phạt cảnh cáo, phạt tiền 5–10 triệu hoặc cải tạo không giam giữ đến 06 tháng',
        applies: 'Say rượu hát karaoke giữa lòng đường, chắn xe, gây náo loạn',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 260',
        name: 'Tội vi phạm quy định về tham gia giao thông đường bộ',
        clause: 'Khoản 2 điểm đ',
        text: 'Lái xe ô tô, mô tô, xe gắn máy, xe máy điện hoặc các loại xe tương tự mà trong cơ thể có nồng độ cồn vượt quy định — phạt tù từ 01 năm đến 05 năm; nếu gây tai nạn hoặc hậu quả nghiêm trọng — phạt tù từ 03 năm đến 10 năm.',
        penalty: 'Tù 01 – 05 năm; 03 – 10 năm nếu gây hậu quả nghiêm trọng',
        applies: 'Uống rượu rồi lái xe về — nhắc nhở cuối clip, song song gây rối đường phố',
      },
    ],
    production: 'Physical comedy 3-vs-1 bắt buộc. Outro: "BLHS Điều 318 K1 + Điều 260 K2đ". Drone giả khi chắn đường.',
    sampleCaption: 'Say hát giữa đường — 3 người kéo không nổi! Điều 318 + 260 đợi sẵn 🍺 #SayKhongGayRoi',
    hashtags: '#BinhXangCon #SayKhongGayRoi #Dieu318BLHS #Dieu260BLHS #CongAnPhuongPhuongLiet',
  },
  {
    id: 10,
    title: 'Thấy Mà Im - Hối Hận Muộn Màng',
    subtitle: 'Tố giác tội phạm — trách nhiệm cộng đồng',
    category: 'to-giac',
    categoryLabel: 'Tố giác & Cảnh giác',
    scene: 'home',
    hook: 'Hôm nay im lặng — Ngày mai nhà mình 🏠',
    duration: '44 giây',
    location: 'Khu tập thể Phương Liệt',
    mood: 'Emotional premium → Time jump twist → Outro HP+BLTTHS+BLHS',
    viralScore: 98,
    viralLikes: '35.8K',
    viralComments: '1.3K',
    summary:
      'Clip cảm xúc premium nhất bộ: BXC ban công thấy trộm xe hàng xóm — quay đi làm ngơ. Time jump "3 ngày sau" — nhà mình bị đột nhập, mặt "trăm ngàn lỗi lầm". Chạy đến Công an Phường Phương Liệt tố giác. Outro Voiceover: Hiến pháp 2013 Điều 15 K4 + BLTTHS Điều 143 K1 + BLHS Điều 173 K1–2.',
    storyboard: [
      { time: '0:00', title: 'Hook chứng kiến', desc: 'BXC ban công, nhìn kẻ trộm xe hàng xóm — text 3 giây.', overlay: 'Thấy mà... im lặng? 😶' },
      { time: '0:10', title: 'Làm ngơ', desc: 'Quay đi, nhún vai "không liên quan", đóng cửa ban công.', overlay: 'Không muốn dính líu — Sai lầm lớn' },
      { time: '0:18', title: 'Time jump', desc: '"3 ngày sau" — BXC mở cửa, nhà lộn xộn, tủ mở toang.', overlay: 'Hôm nay im — Ngày mai là mình 🏠' },
      { time: '0:30', title: 'Hối hận & tố giác', desc: 'BXC chạy đến trụ sở Công an Phương Liệt — cảm xúc thật.', overlay: 'Thấy mà báo — Ngay lập tức!' },
      { time: '0:40', title: 'Outro pháp lý', desc: 'Hotline tố giác + 3 điều luật overlay full màn.', overlay: 'Cùng nhau an toàn 💙', legalOutro: 'HP 2013 Điều 15 K4 + BLTTHS Điều 143 K1 + BLHS Điều 173 K1–2' },
    ],
    dialogues: [
      { speaker: 'BXC (VO)', line: 'Hôm qua trộm nhà người ta, tôi im lặng. Hôm nay... cửa nhà tôi mở toang.' },
      { speaker: 'Hàng xóm (off)', line: 'Sao hôm trước anh không báo?! Giờ cả khu phố lo!' },
      { speaker: 'BXC', line: 'Sao tôi không báo hôm đó... Giờ muộn rồi... Nhưng em vẫn phải nói!' },
      { speaker: 'Công an', line: 'Anh tố giác là đúng. Lần sau thấy khả nghi — báo ngay, bảo vệ cả hàng xóm lẫn chính mình.' },
      { speaker: 'Voiceover', line: 'Hiến pháp 2013 Điều 15 Khoản 4: Công dân có nghĩa vụ tuân thủ pháp luật, tham gia bảo vệ an ninh, trật tự — tố giác tội phạm là trách nhiệm cộng đồng.' },
      { speaker: 'Voiceover', line: 'BLTTHS Điều 143 K1: Cơ quan Công an tiếp nhận mọi tố giác, tin báo. BLHS Điều 173 K1–2: Trộm cắp, đột nhập nhà — tù 06 tháng đến 07 năm tùy tình tiết.' },
    ],
    script: [
      '【0-3s | HOOK】BXC ban công khu tập thể Phương Liệt, nhìn kẻ trộm xe hàng xóm. Text: "Thấy mà im lặng?".',
      '【3-12s】Quay đi, nhún vai "không liên quan", đóng cửa. Nhạc buồn nhẹ — guilt building.',
      '【12-24s | TIME JUMP】Text lớn "3 NGÀY SAU". BXC mở cửa — nhà lộn xộn, freeze face 2 giây.',
      '【24-34s】BXC chạy đến trụ sở Công an Phường Phương Liệt. Handheld cảm xúc — không over-act.',
      '【34-44s | OUTRO | HP Điều 15 K4 + BLTTHS Điều 143 K1 + BLHS Điều 173 K1–2】Hotline tố giác on screen. Voiceover đọc 3 điều luật. Text: "Im lặng = Dung túng. Thấy mà báo." Logo Công an Phường Phương Liệt.',
    ],
    role: 'Người chứng kiến thờ ơ — arc cảm xúc premium: indifferent → hối hận cá nhân → hành động tố giác.',
    message: 'Tố giác tội phạm = quyền và trách nhiệm công dân theo Hiến pháp. Im lặng giúp tội phạm tái phạm — hôm nay nhà người, ngày mai nhà mình.',
    cta: 'Thấy khả nghi → Gọi 113 hoặc hotline Công an Phường Phương Liệt. Có thể tố giác ẩn danh theo BLTTHS.',
    legalNote:
      'Tố giác tội phạm — Hiến pháp 2013 Điều 15 Khoản 4 (nghĩa vụ bảo vệ an ninh trật tự); BLTTHS Điều 143 Khoản 1 (tiếp nhận tố giác). Đột nhập, trộm cắp nhà: BLHS Điều 173 Khoản 1 (tù 06 tháng – 03 năm), Khoản 2 (tù 02–07 năm nếu tổ chức/giá trị lớn).',
    legalArticles: [
      {
        code: 'Hiến pháp 2013',
        law: LAW_REF.HP,
        article: 'Điều 15',
        name: 'Quyền và nghĩa vụ cơ bản của công dân',
        clause: 'Khoản 4',
        text: 'Mọi người có trách nhiệm tôn trọng pháp luật; công dân có nghĩa vụ bảo vệ Tổ quốc, tuân thủ pháp luật, tham gia bảo vệ an ninh, trật tự, an toàn xã hội.',
        penalty: 'Không xử phạt người tố giác trung thực',
        applies: 'Thấy trộm, đột nhập — báo Công an ngay, không làm ngơ vì "sợ dính líu"',
      },
      {
        code: 'BLTTHS 2015',
        law: LAW_REF.BLTTHS,
        article: 'Điều 143',
        name: 'Tố giác, tin báo về tội phạm',
        clause: 'Khoản 1',
        text: 'Mọi công dân có quyền tố giác, báo tin về tội phạm đến cơ quan Công an, Viện kiểm sát hoặc Tòa án. Cơ quan có trách nhiệm tiếp nhận, xử lý kịp thời theo quy định của Bộ luật này.',
        penalty: 'Người tố giác được bảo vệ theo Điều 144 BLTTHS',
        applies: 'Gọi 113 hoặc đến Công an Phường Phương Liệt tố giác trộm, đột nhập',
      },
      {
        code: 'BLHS 2015',
        law: LAW_REF.BLHS,
        article: 'Điều 173',
        name: 'Tội trộm cắp tài sản (đột nhập)',
        clause: 'Khoản 1–2',
        text: 'Khoản 1: Trộm cắp tài sản từ 2 triệu đến dưới 50 triệu — tù 06 tháng – 03 năm. Khoản 2: Trộm cắp có tổ chức, chuyên nghiệp hoặc tài sản 50–200 triệu — tù 02–07 năm.',
        penalty: 'Tù 06 tháng – 07 năm tùy tình tiết',
        applies: 'Đột nhập nhà, trộm xe trong khu tập thể Phương Liệt',
      },
    ],
    production: 'Time jump "3 ngày sau" bắt buộc. Outro: "HP Điều 15 K4 + BLTTHS Điều 143 K1 + BLHS Điều 173 K1–2". Emotional handheld, không melodrama.',
    sampleCaption: 'Im lặng hôm qua — nhà mình hôm nay 😢 HP Điều 15 + BLTTHS 143 + BLHS 173! #ThayMaBao',
    hashtags: '#BinhXangCon #ThayMaBao #HienPhap2013 #Dieu143BLTTHS #Dieu173BLHS #CongAnPhuongPhuongLiet',
  },
];